#!/bin/bash
robotnum=1
robotstart=0
appname=robot
logroot=~/log
fileconf=../conf/conf_${appname}.json
servername=${appname}
logname=${servername}.log
logpath=${logroot}/${servername}
daemonlog=$logroot/daemon.${servername}.log


if [ -n "$1" ]    #如果参数不是空
then
    robotnum=$1
fi

if [ -n "$2" ]
then
    robotstart=$2
fi

## 老版本
#./robot -conf=../conf/conf_robot.json -logname=robot.log -logpath=../../log/robot/ -num=$robotnum -start=$robotstart -daemon=false
#./robot -conf=../conf/conf_robot.json -logname=robot.log -logpath=../../log/robot/ -num=$robotnum -start=$robotstart -daemon=true > $daemonlog 2>&1 &

## 前台运行
./${servername} -conf=${fileconf} -logname=${logname} -logpath=${logpath} -num=$robotnum -start=$robotstart -daemon=false

## 后台运行
#./${servername} -conf=${fileconf} -logname=${logname} -logpath=${logpath} -num=$robotnum -start=$robotstart -daemon=true > $daemonlog 2>&1 &

