// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TNotice : table.ITNoticeDefine[] = [
		{ Id : 1, Avatar : 1, Info : "欢迎来到跳娃娃！" 	},
		{ Id : 2, Avatar : 1, Info : "来玩就送，实物大奖领回家！" 	},
		{ Id : 3, Avatar : 1, Info : "天天签到送元宝！" 	}
	]


// Id
export var TNoticeById : game.Dictionary<table.ITNoticeDefine> = {}
function readTNoticeById(){
  for(let rec of TNotice) {
    TNoticeById[rec.Id] = rec; 
  }
}
readTNoticeById();
}

