// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TBirckItem : table.ITBirckItemDefine[] = [
		{ Id : 1, Name : "分身球", Num : 1, Pro : 0 	},
		{ Id : 2, Name : "加长板", Num : 1, Pro : 0 	},
		{ Id : 3, Name : "元宝", Num : 1, Pro : 0 	}
	]


// Id
export var TBirckItemById : game.Dictionary<table.ITBirckItemDefine> = {}
function readTBirckItemById(){
  for(let rec of TBirckItem) {
    TBirckItemById[rec.Id] = rec; 
  }
}
readTBirckItemById();
}

