// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TBirckRefresh : table.ITBirckRefreshDefine[] = [
		{ Id : 1, Min : 0, Max : 99999999, Pro : "1-400;2-200;3-200;4-100;5-40;21-6", Limitnum : 10 	}
	]


// Id
export var TBirckRefreshById : game.Dictionary<table.ITBirckRefreshDefine> = {}
function readTBirckRefreshById(){
  for(let rec of TBirckRefresh) {
    TBirckRefreshById[rec.Id] = rec; 
  }
}
readTBirckRefreshById();
}

