-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.10

local tab = {
	TRecharge = {
		{ Id = 1, Price = 6 	},
		{ Id = 2, Price = 12 	},
		{ Id = 3, Price = 30 	},
		{ Id = 4, Price = 68 	},
		{ Id = 5, Price = 128 	},
		{ Id = 6, Price = 348 	},
		{ Id = 7, Price = 648 	}
	}

}


-- Id
tab.TRechargeById = {}
for _, rec in pairs(tab.TRecharge) do
	tab.TRechargeById[rec.Id] = rec
end

tab.Enum = {
}

return tab