// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TBallGift : table.ITBallGiftDefine[] = [
		{ Id : 1, Name : "奖品1", Path : "", Pro : 1000 	},
		{ Id : 2, Name : "奖品2", Path : "", Pro : 1000 	},
		{ Id : 3, Name : "奖品3", Path : "", Pro : 1000 	},
		{ Id : 4, Name : "奖品4", Path : "", Pro : 1000 	},
		{ Id : 5, Name : "奖品5", Path : "", Pro : 1000 	},
		{ Id : 6, Name : "奖品6", Path : "", Pro : 1000 	},
		{ Id : 7, Name : "奖品7", Path : "", Pro : 1000 	},
		{ Id : 8, Name : "奖品8", Path : "", Pro : 1000 	},
		{ Id : 9, Name : "奖品9", Path : "", Pro : 500 	},
		{ Id : 10, Name : "奖品10", Path : "", Pro : 500 	},
		{ Id : 11, Name : "奖品11", Path : "", Pro : 500 	},
		{ Id : 12, Name : "奖品12", Path : "", Pro : 500 	}
	]


// Id
export var TBallGiftById : game.Dictionary<table.ITBallGiftDefine> = {}
function readTBallGiftById(){
  for(let rec of TBallGift) {
    TBallGiftById[rec.Id] = rec; 
  }
}
readTBallGiftById();
}

