// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TBallGift : table.ITBallGiftDefine[] = [
		{ Id : 1, Name : "100金币", Num : 100, ItemId : 6003, Path : "item/6003", Pro : 1334, PushBag : 1, Cost : 100 	},
		{ Id : 2, Name : "50元京东卡", Num : 1, ItemId : 2006, Path : "item/2006", Pro : 50, PushBag : 1, Cost : 50 	},
		{ Id : 3, Name : "10元电话卡", Num : 1, ItemId : 5004, Path : "item/5004", Pro : 100, PushBag : 1, Cost : 10 	},
		{ Id : 4, Name : "1000金币", Num : 1000, ItemId : 6003, Path : "item/6003", Pro : 1000, PushBag : 1, Cost : 1000 	},
		{ Id : 5, Name : "500金币", Num : 500, ItemId : 6003, Path : "item/6003", Pro : 1000, PushBag : 1, Cost : 500 	},
		{ Id : 6, Name : "黄金吊坠", Num : 1, ItemId : 3018, Path : "item/3018", Pro : 5, PushBag : 1, Cost : 840 	},
		{ Id : 7, Name : "2000金币", Num : 2000, ItemId : 6003, Path : "item/6003", Pro : 350, PushBag : 1, Cost : 2000 	},
		{ Id : 8, Name : "200元京东卡", Num : 1, ItemId : 2004, Path : "item/2004", Pro : 10, PushBag : 1, Cost : 200 	},
		{ Id : 9, Name : "5000金币", Num : 5000, ItemId : 6003, Path : "item/6003", Pro : 200, PushBag : 1, Cost : 5000 	},
		{ Id : 10, Name : "iPhone X", Num : 1, ItemId : 1001, Path : "item/1001", Pro : 1, PushBag : 1, Cost : 8488 	},
		{ Id : 11, Name : "200金币", Num : 200, ItemId : 6003, Path : "item/6003", Pro : 1200, PushBag : 1, Cost : 200 	},
		{ Id : 12, Name : "30元电话卡", Num : 1, ItemId : 5003, Path : "item/5003", Pro : 100, PushBag : 1, Cost : 30 	},
		{ Id : 13, Name : "100金币", Num : 100, ItemId : 6003, Path : "item/6003", Pro : 1300, PushBag : 1, Cost : 100 	},
		{ Id : 14, Name : "50元京东卡", Num : 1, ItemId : 2006, Path : "item/2006", Pro : 50, PushBag : 1, Cost : 50 	},
		{ Id : 15, Name : "10元电话卡", Num : 1, ItemId : 5004, Path : "item/5004", Pro : 100, PushBag : 1, Cost : 10 	},
		{ Id : 16, Name : "1000金币", Num : 1000, ItemId : 6003, Path : "item/6003", Pro : 1000, PushBag : 1, Cost : 1000 	},
		{ Id : 17, Name : "500金币", Num : 500, ItemId : 6003, Path : "item/6003", Pro : 1000, PushBag : 1, Cost : 500 	},
		{ Id : 18, Name : "200金币", Num : 200, ItemId : 6003, Path : "item/6003", Pro : 1200, PushBag : 1, Cost : 200 	}
	]


// Id
export var TBallGiftById : game.Dictionary<table.ITBallGiftDefine> = {}
function readTBallGiftById(){
  for(let rec of TBallGift) {
    TBallGiftById[rec.Id] = rec; 
  }
}
readTBallGiftById();
}

