// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TBirckRefresh : table.ITBirckRefreshDefine[] = [
		{ Id : 1, Min : 0, Max : 99999999, Pro : "1-40;2-20;3-20;4-20;5-100", Limitnum : 0 	}
	]


// Id
export var TBirckRefreshById : game.Dictionary<table.ITBirckRefreshDefine> = {}
function readTBirckRefreshById(){
  for(let rec of TBirckRefresh) {
    TBirckRefreshById[rec.Id] = rec; 
  }
}
readTBirckRefreshById();
}

