// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TFootBall : table.ITFootBallDefine[] = [
		{ Id : 10001, ShowPer : 500, ItemValue : 1000, Reward : 150, Notice : 1 	},
		{ Id : 5004, ShowPer : 50, ItemValue : 2400, Reward : 100, Notice : 1 	},
		{ Id : 5003, ShowPer : 50, ItemValue : 7200, Reward : 100, Notice : 1 	},
		{ Id : 2006, ShowPer : 50, ItemValue : 12000, Reward : 100, Notice : 1 	},
		{ Id : 5001, ShowPer : 50, ItemValue : 24000, Reward : 100, Notice : 1 	},
		{ Id : 7005, ShowPer : 50, ItemValue : 2400, Reward : 100, Notice : 1 	},
		{ Id : 4005, ShowPer : 50, ItemValue : 9600, Reward : 100, Notice : 1 	},
		{ Id : 4004, ShowPer : 50, ItemValue : 11760, Reward : 100, Notice : 1 	},
		{ Id : 4011, ShowPer : 50, ItemValue : 14160, Reward : 100, Notice : 1 	},
		{ Id : 4026, ShowPer : 50, ItemValue : 720, Reward : 100, Notice : 1 	},
		{ Id : 4018, ShowPer : 50, ItemValue : 16320, Reward : 100, Notice : 1 	}
	]


// Id
export var TFootBallById : game.Dictionary<table.ITFootBallDefine> = {}
function readTFootBallById(){
  for(let rec of TFootBall) {
    TFootBallById[rec.Id] = rec; 
  }
}
readTFootBallById();
}

