// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TGiftPro : table.ITGiftProDefine[] = [
		{ Id : 1, Limitmin : 0, Limitmax : 0, Pro : [ "1-1250", "2-1000", "3-750", "4-750", "5-500", "6-500", "7-390", "8-250", "9-200", "10-100", "11-25", "12-10", "13-1250", "14-1000", "15-750", "16-750", "17-500", "18-25" ] 	},
		{ Id : 2, Limitmin : 1, Limitmax : 200, Pro : [ "1-1250", "2-1000", "3-750", "4-750", "5-500", "6-500", "7-390", "8-250", "9-200", "10-100", "11-25", "12-10", "13-1250", "14-1000", "15-750", "16-750", "17-500", "18-25" ] 	},
		{ Id : 3, Limitmin : 200, Limitmax : 999999, Pro : [ "1-1250", "2-1000", "3-750", "4-750", "5-500", "6-500", "7-390", "8-250", "9-200", "10-100", "11-25", "12-10", "13-1250", "14-1000", "15-750", "16-750", "17-500", "18-25" ] 	}
	]


// Id
export var TGiftProById : game.Dictionary<table.ITGiftProDefine> = {}
function readTGiftProById(){
  for(let rec of TGiftPro) {
    TGiftProById[rec.Id] = rec; 
  }
}
readTGiftProById();
}

