// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var ItemBaseData : table.IItemBaseDataDefine[] = [
		{ Id : 1012, Name : "荣耀体脂称", Desc : "名称:荣耀蓝牙APP智能电子秤 特征:智能体脂秤 描述:适配ios&安卓 类型:固定发货", Sort : 21, Type : 1, Sold : 199, RealPrice : 1990 	},
		{ Id : 1013, Name : "小方智能摄像机", Desc : "名称:小方智能摄像机 特征:1080p 描述:白色 类型:固定发货", Sort : 26, Type : 1, Sold : 139, RealPrice : 1390 	},
		{ Id : 1015, Name : "小米手环", Desc : "名称:小米手环 特征:手环 描述:京东自营店 类型:随机发货", Sort : 51, Type : 1, Sold : 149, RealPrice : 1490 	},
		{ Id : 2001, Name : "京东e卡1000元", Desc : "名称:京东卡 特征:1000 描述:虚拟卡 类型:固定发货", Sort : 15, Type : 2, Sold : 1000, RealPrice : 10000 	},
		{ Id : 2002, Name : "京东e卡500元", Desc : "名称:京东卡 特征:500 描述:虚拟卡 类型:固定发货", Sort : 22, Type : 2, Sold : 500, RealPrice : 5000 	},
		{ Id : 2003, Name : "京东e卡300元", Desc : "名称:京东卡 特征:300 描述:虚拟卡 类型:固定发货", Sort : 30, Type : 2, Sold : 300, RealPrice : 3000 	},
		{ Id : 2004, Name : "京东e卡200元", Desc : "名称:京东卡 特征:200 描述:虚拟卡 类型:固定发货", Sort : 37, Type : 2, Sold : 200, RealPrice : 2000 	},
		{ Id : 2006, Name : "京东e卡50元", Desc : "名称:京东卡 特征:50 描述:虚拟卡 类型:固定发货", Sort : 77, Type : 2, Sold : 50, RealPrice : 500 	},
		{ Id : 3004, Name : "花王蒸汽眼罩", Desc : "名称:花王蒸汽眼罩（无香） 特征:170g 描述:14片 类型:固定发货", Sort : 17, Type : 3, Sold : 78, RealPrice : 780 	},
		{ Id : 3008, Name : "施耐福四件套", Desc : "名称:施耐福 黑色四件套 特征: 黑色四件套 描述:不锈钢钢 类型:固定发货", Sort : 36, Type : 3, Sold : 248, RealPrice : 2480 	},
		{ Id : 3009, Name : "镁离子净水壶", Desc : "名称:镁离子净水壶 特征:1.5升 描述:PP树脂 类型:固定发货", Sort : 40, Type : 3, Sold : 189, RealPrice : 1890 	},
		{ Id : 3010, Name : "德尔玛加湿器", Desc : "名称:德尔玛加湿器 特征:5升 描述:PP树脂 类型:固定发货", Sort : 45, Type : 3, Sold : 80, RealPrice : 800 	},
		{ Id : 3012, Name : "小熊咖啡机", Desc : "名称:小熊机 美式家用咖啡壶 特征:0.7L 描述:滴滤机 类型:固定发货", Sort : 56, Type : 3, Sold : 129, RealPrice : 1290 	},
		{ Id : 3013, Name : "忠臣电陶炉", Desc : "名称:忠臣电陶炉 特征:电陶炉 描述:黑色 类型:固定发货", Sort : 57, Type : 3, Sold : 199, RealPrice : 1990 	},
		{ Id : 3014, Name : "金正养生壶", Desc : "名称:金正养生壶 特征:1.5L 描述:养生壶 类型:固定发货", Sort : 62, Type : 3, Sold : 99, RealPrice : 990 	},
		{ Id : 3015, Name : "九洲鹿床垫", Desc : "名称:九洲鹿床垫 特征:床垫 描述:棉 类型:固定发货", Sort : 65, Type : 3, Sold : 78, RealPrice : 780 	},
		{ Id : 3016, Name : "悠佳脏衣篮", Desc : "名称:悠佳脏衣篮 特征:40升 描述:PP树脂 类型:固定发货", Sort : 67, Type : 3, Sold : 79, RealPrice : 790 	},
		{ Id : 3019, Name : "南极人四件套", Desc : "名称:南极人四件套 特征:四件套 描述:棉 类型:固定发货", Sort : 74, Type : 3, Sold : 149, RealPrice : 1490 	},
		{ Id : 3021, Name : "小熊养生壶", Desc : "名称:小熊养生壶 特征:1.5L 描述:养生壶 类型:固定发货", Sort : 86, Type : 3, Sold : 129, RealPrice : 1290 	},
		{ Id : 4002, Name : "Disney维尼熊", Desc : "名称:小熊维尼公仔 特征:高约52cm 描述:PP棉 类型:固定发货", Sort : 18, Type : 4, Sold : 198, RealPrice : 1980 	},
		{ Id : 4004, Name : "创意十二萌犬", Desc : "名称:创意十二萌犬礼盒 特征:树脂 描述:饰物 类型:固定发货", Sort : 25, Type : 4, Sold : 49, RealPrice : 490 	},
		{ Id : 4005, Name : "迪士尼布鲁托", Desc : "名称:正版迪士尼布鲁托 特征:30-35cm 描述:PP棉 类型:固定发货", Sort : 27, Type : 4, Sold : 40, RealPrice : 400 	},
		{ Id : 4010, Name : "仿真狗boo", Desc : "名称:仿真狗boo 特征:60cm 描述:PP棉 类型:固定发货", Sort : 42, Type : 4, Sold : 199, RealPrice : 1990 	},
		{ Id : 4011, Name : "大脸猫玩偶", Desc : "名称:白色泪眼猫 特征:60cm 描述:PP棉 类型:固定发货", Sort : 47, Type : 4, Sold : 59, RealPrice : 590 	},
		{ Id : 4013, Name : "冰雪奇缘艾莎", Desc : "名称:冰雪奇缘-艾莎 特征:28cm 描述:玩偶 类型:固定发货", Sort : 55, Type : 4, Sold : 99, RealPrice : 990 	},
		{ Id : 4015, Name : "节日版维尼熊", Desc : "名称:正版迪士尼维尼熊 特征:41cm 描述:PP棉 类型:固定发货", Sort : 60, Type : 4, Sold : 129, RealPrice : 1290 	},
		{ Id : 4017, Name : "粉红豹公仔", Desc : "名称:粉红顽皮豹 特征:55cm 描述:PP棉 类型:固定发货", Sort : 64, Type : 4, Sold : 178, RealPrice : 1780 	},
		{ Id : 4018, Name : "哈姆太郎", Desc : "名称:哈姆太郎 特征:40cm 描述:毛绒 类型:固定发货", Sort : 71, Type : 4, Sold : 68, RealPrice : 680 	},
		{ Id : 4022, Name : "皮卡丘玩偶", Desc : "名称:大型抱抱熊公仔 特征:90cm 描述:PP棉 类型:固定发货", Sort : 83, Type : 4, Sold : 100, RealPrice : 1000 	},
		{ Id : 4023, Name : "音乐泰迪熊", Desc : "名称:七彩发光音乐泰迪熊 特征:100cm 描述:PP棉 类型:固定发货", Sort : 87, Type : 4, Sold : 178, RealPrice : 1780 	},
		{ Id : 4024, Name : "人形抱枕", Desc : "名称:索尼子人形抱枕 特征:160*50cm 描述:PP棉 类型:固定发货", Sort : 88, Type : 4, Sold : 298, RealPrice : 2980 	},
		{ Id : 4025, Name : "巡音人形抱枕", Desc : "名称:巡音人形抱枕 特征:160*50cm 描述:PP棉 类型:固定发货", Sort : 92, Type : 4, Sold : 298, RealPrice : 2980 	},
		{ Id : 4026, Name : "随机娃娃", Desc : "名称:小礼品 特征:时尚小挂件一个 描述:多种款式 类型:随机发货", Sort : 94, Type : 9, Sold : 3, RealPrice : 30 	},
		{ Id : 5001, Name : "100元话费", Desc : "名称:话费直充 特征:100元 描述:虚拟卡 类型:固定发货", Sort : 59, Type : 5, Sold : 100, RealPrice : 1000 	},
		{ Id : 5002, Name : "50元话费", Desc : "名称:话费直充 特征:50 描述:虚拟卡 类型:固定发货", Sort : 76, Type : 5, Sold : 50, RealPrice : 500 	},
		{ Id : 5003, Name : "30元话费", Desc : "名称:话费直充 特征:30 描述:虚拟卡 类型:固定发货", Sort : 84, Type : 5, Sold : 30, RealPrice : 300 	},
		{ Id : 5004, Name : "10元话费", Desc : "名称:话费直充 特征:10元 描述:虚拟卡 类型:固定发货", Sort : 91, Type : 5, Sold : 10, RealPrice : 100 	},
		{ Id : 7001, Name : "PAPAGO记录仪", Desc : "名称:PAPAGO行车记录仪 特征：超高清 描述：迷你隐藏式 类型：固定发货", Sort : 12, Type : 7, Sold : 289, RealPrice : 2890 	},
		{ Id : 7004, Name : "汽车腰靠垫", Desc : "名称:汽车腰靠垫 特征：倍逸舒 描述：人体工学 类型：固定发货", Sort : 34, Type : 7, Sold : 189, RealPrice : 1890 	},
		{ Id : 7005, Name : "车载手机支架", Desc : "名称:车载手机支架 特征：塑料 描述：风口式支架 类型：固定发货", Sort : 38, Type : 7, Sold : 10, RealPrice : 100 	},
		{ Id : 7006, Name : "车载充电器", Desc : "名称:车载充电器 特征：银色 描述：全金属 类型：固定发货", Sort : 44, Type : 7, Sold : 26, RealPrice : 260 	},
		{ Id : 7009, Name : "汽车头枕腰靠", Desc : "名称:汽车腰靠垫 特征：织物 描述：人体工学 类型：固定发货", Sort : 53, Type : 7, Sold : 179, RealPrice : 1790 	},
		{ Id : 7010, Name : "车载充电器", Desc : "名称:飞利浦车载充电器 特征:双USB输出 描述:黑色 类型:固定发货", Sort : 54, Type : 7, Sold : 129, RealPrice : 1290 	},
		{ Id : 7012, Name : "海尔净化器", Desc : "名称:车载空气净化器 特征:CJ05A 描述:便携式 类型:固定发货", Sort : 66, Type : 7, Sold : 199, RealPrice : 1990 	},
		{ Id : 7013, Name : "车载吸尘器", Desc : "名称:车载吸尘器 特征:12V 描述:黑金色 类型:固定发货", Sort : 70, Type : 7, Sold : 79, RealPrice : 790 	},
		{ Id : 7018, Name : "汽车U盘", Desc : "名称:车载mp3汽车U盘带音乐 特征:32g 描述:金色 类型:固定发货", Sort : 85, Type : 7, Sold : 59, RealPrice : 590 	},
		{ Id : 7019, Name : "汽车收纳箱", Desc : "名称:汽车收纳箱储物箱 特征:40升 描述:PP树脂 类型:固定发货", Sort : 90, Type : 7, Sold : 129, RealPrice : 1290 	},
		{ Id : 10001, Name : "钻石", Desc : "名称：红包通用钻石", Sort : 95, Type : 10, Sold : 0, RealPrice : 100 	},
		{ Id : 10002, Name : "钻石券", Desc : "名称：10张钻石券可兑换1个钻石", Sort : 96, Type : 10, Sold : 0, RealPrice : 10 	}
	]


// Id
export var ItemBaseDataById : game.Dictionary<table.IItemBaseDataDefine> = {}
function readItemBaseDataById(){
  for(let rec of ItemBaseData) {
    ItemBaseDataById[rec.Id] = rec; 
  }
}
readItemBaseDataById();
}

