// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TTurntableNew : table.ITTurntableNewDefine[] = [
		{ Id : 1, Nums : "0;1;2;3;4;5;6;1;2;0", Max : 6 	},
		{ Id : 2, Nums : "0;1;2;3;4;5;6;1;2;0", Max : 6 	}
	]


// Id
export var TTurntableNewById : game.Dictionary<table.ITTurntableNewDefine> = {}
function readTTurntableNewById(){
  for(let rec of TTurntableNew) {
    TTurntableNewById[rec.Id] = rec; 
  }
}
readTTurntableNewById();
}

