// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	account.proto
	battle.proto
	clientgate.proto
	clientlogin.proto
	define.proto
	gatelogin.proto
	gatematch.proto
	gateroom.proto
	item.proto
	matchroom.proto
	notice.proto
	serialize.proto
	server.proto
	user.proto

It has these top-level messages:
	AccountInfo
	AccountGateInfo
	BattleUser
	GridItem
	BT_UploadGameUser
	BT_ReqEnterRoom
	BT_GameInit
	BT_SendBattleUser
	BT_GameStart
	BT_GameEnd
	BT_GameOver
	BT_JumpPreCheck
	BT_RetJumpPreCheck
	BT_ReqJumpStep
	BT_RetJumpStep
	BT_ReqQuitGameRoom
	BT_PickItem
	C2GW_ReqLogin
	GW2C_RetLogin
	GW2C_SendUserInfo
	GW2C_SendUserPlatformMoney
	C2GW_HeartBeat
	GW2C_HeartBeat
	C2GW_ReqStartGame
	GW2C_RetStartGame
	GW2C_Ret7DayReward
	C2GW_Get7DayReward
	C2L_ReqLogin
	L2C_RetLogin
	C2L_ReqRegistAccount
	L2C_RetRegistAccount
	IpHost
	PairNumItem
	GW2L_ReqRegist
	L2GW_RetRegist
	GW2L_HeartBeat
	L2GW_HeartBeat
	L2GW_ReqRegistUser
	GW2L_RegistUserRet
	GW2MS_ReqRegist
	MS2GW_RetRegist
	GW2MS_HeartBeat
	MS2GW_HeartBeat
	GW2MS_ReqCreateRoom
	MS2GW_RetCreateRoom
	RS2GW_ReqRegist
	GW2RS_RetRegist
	GW2RS_UserDisconnect
	RS2GW_RetUserDisconnect
	C2GW_BuyItem
	GW2C_AddPackageItem
	GW2C_RemovePackageItem
	GW2C_UpdateYuanbao
	GW2C_UpdateCoupon
	GW2C_UpdateFreeStep
	DeliveryGoods
	C2GW_ReqDeliveryGoods
	C2GW_ReqDeliveryDiamond
	GW2C_RetDeliveryDiamond
	BigRewardItem
	Sync_BigRewardPickNum
	C2GW_UseBagItem
	C2GW_SellBagItem
	RS2MS_ReqRegist
	MS2RS_RetRegist
	RS2MS_HeartBeat
	MS2RS_HeartBeat
	GateSimpleInfo
	MS2RS_GateInfo
	MS2RS_CreateRoom
	RS2MS_RetCreateRoom
	RS2MS_DeleteRoom
	RS2MS_UpdateRewardPool
	GW2C_MsgNotify
	GW2C_MsgNotice
	GW2MS_MsgNotice
	RS2MS_MsgNotice
	MS2GW_MsgNotice
	EntityBase
	SimpleCounter
	UserBase
	UserAddress
	ItemData
	ItemBin
	Serialize
	MS2Server_BroadCast
	C2GW_AddDeliveryAddress
	C2GW_DelDeliveryAddress
	C2GW_ChangeDeliveryAddress
	GW2C_SendDeliveryAddressList
	C2GW_ReqRechargeMoney
	GW2C_RetRechargeMoney
	C2GW_PlatformRechargeDone
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountInfo struct {
	Account *string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Passwd  *string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	// optional string phone  = 3;
	// optional string idcard = 4;
	Userid           *uint64 `protobuf:"varint,5,opt,name=userid" json:"userid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountInfo) Reset()                    { *m = AccountInfo{} }
func (m *AccountInfo) String() string            { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()               {}
func (*AccountInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountInfo) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *AccountInfo) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *AccountInfo) GetUserid() uint64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

type AccountGateInfo struct {
	Ip               *string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port             *int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Verifykey        *string `protobuf:"bytes,3,opt,name=verifykey" json:"verifykey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountGateInfo) Reset()                    { *m = AccountGateInfo{} }
func (m *AccountGateInfo) String() string            { return proto.CompactTextString(m) }
func (*AccountGateInfo) ProtoMessage()               {}
func (*AccountGateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountGateInfo) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *AccountGateInfo) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *AccountGateInfo) GetVerifykey() string {
	if m != nil && m.Verifykey != nil {
		return *m.Verifykey
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountInfo)(nil), "msg.AccountInfo")
	proto.RegisterType((*AccountGateInfo)(nil), "msg.AccountGateInfo")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0xb2,
	0xe3, 0xe2, 0x76, 0x84, 0x88, 0x7a, 0xe6, 0xa5, 0xe5, 0x0b, 0xf1, 0x73, 0xb1, 0x43, 0x15, 0x49,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x0a, 0xf1, 0x71, 0xb1, 0x15, 0x24, 0x16, 0x17, 0x97, 0xa7, 0x48,
	0x30, 0xc1, 0xf8, 0xa5, 0xc5, 0xa9, 0x45, 0x99, 0x29, 0x12, 0xac, 0x0a, 0x8c, 0x1a, 0x2c, 0x4a,
	0x76, 0x5c, 0xfc, 0x50, 0xfd, 0xee, 0x89, 0x25, 0xa9, 0x60, 0x33, 0xb8, 0xb8, 0x98, 0x32, 0x0b,
	0xa0, 0xda, 0x79, 0xb8, 0x58, 0x0a, 0xf2, 0x8b, 0x4a, 0xc0, 0x9a, 0x59, 0x85, 0x04, 0xb9, 0x38,
	0xcb, 0x52, 0x8b, 0x32, 0xd3, 0x2a, 0xb3, 0x53, 0x2b, 0x25, 0x98, 0x41, 0x0a, 0x00, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x8e, 0x41, 0x1a, 0x67, 0x94, 0x00, 0x00, 0x00,
}
