// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clientgate.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 客户端请求登陆网关
type C2GW_ReqLogin struct {
	Account          *string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Verifykey        *string `protobuf:"bytes,2,opt,name=verifykey" json:"verifykey,omitempty"`
	Token            *string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	Face             *string `protobuf:"bytes,4,opt,name=face" json:"face,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GW_ReqLogin) Reset()                    { *m = C2GW_ReqLogin{} }
func (m *C2GW_ReqLogin) String() string            { return proto.CompactTextString(m) }
func (*C2GW_ReqLogin) ProtoMessage()               {}
func (*C2GW_ReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *C2GW_ReqLogin) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *C2GW_ReqLogin) GetVerifykey() string {
	if m != nil && m.Verifykey != nil {
		return *m.Verifykey
	}
	return ""
}

func (m *C2GW_ReqLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *C2GW_ReqLogin) GetFace() string {
	if m != nil && m.Face != nil {
		return *m.Face
	}
	return ""
}

// 结果
type GW2C_RetLogin struct {
	// optional string account = 1;
	Errcode          *string `protobuf:"bytes,1,opt,name=errcode" json:"errcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2C_RetLogin) Reset()                    { *m = GW2C_RetLogin{} }
func (m *GW2C_RetLogin) String() string            { return proto.CompactTextString(m) }
func (*GW2C_RetLogin) ProtoMessage()               {}
func (*GW2C_RetLogin) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GW2C_RetLogin) GetErrcode() string {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return ""
}

// 发送玩家个人数据
type GW2C_SendUserInfo struct {
	Entity           *EntityBase `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
	Base             *UserBase   `protobuf:"bytes,2,opt,name=base" json:"base,omitempty"`
	Item             *ItemBin    `protobuf:"bytes,3,opt,name=item" json:"item,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GW2C_SendUserInfo) Reset()                    { *m = GW2C_SendUserInfo{} }
func (m *GW2C_SendUserInfo) String() string            { return proto.CompactTextString(m) }
func (*GW2C_SendUserInfo) ProtoMessage()               {}
func (*GW2C_SendUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GW2C_SendUserInfo) GetEntity() *EntityBase {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *GW2C_SendUserInfo) GetBase() *UserBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *GW2C_SendUserInfo) GetItem() *ItemBin {
	if m != nil {
		return m.Item
	}
	return nil
}

type GW2C_SendUserPlatformMoney struct {
	Coins            *int32 `protobuf:"varint,1,opt,name=coins" json:"coins,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GW2C_SendUserPlatformMoney) Reset()                    { *m = GW2C_SendUserPlatformMoney{} }
func (m *GW2C_SendUserPlatformMoney) String() string            { return proto.CompactTextString(m) }
func (*GW2C_SendUserPlatformMoney) ProtoMessage()               {}
func (*GW2C_SendUserPlatformMoney) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GW2C_SendUserPlatformMoney) GetCoins() int32 {
	if m != nil && m.Coins != nil {
		return *m.Coins
	}
	return 0
}

// 心跳
type C2GW_HeartBeat struct {
	Uid              *int64   `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Time             *int64   `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Test             []string `protobuf:"bytes,3,rep,name=test" json:"test,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C2GW_HeartBeat) Reset()                    { *m = C2GW_HeartBeat{} }
func (m *C2GW_HeartBeat) String() string            { return proto.CompactTextString(m) }
func (*C2GW_HeartBeat) ProtoMessage()               {}
func (*C2GW_HeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *C2GW_HeartBeat) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *C2GW_HeartBeat) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *C2GW_HeartBeat) GetTest() []string {
	if m != nil {
		return m.Test
	}
	return nil
}

type GW2C_HeartBeat struct {
	Uid              *int64   `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Time             *int64   `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Test             []string `protobuf:"bytes,3,rep,name=test" json:"test,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GW2C_HeartBeat) Reset()                    { *m = GW2C_HeartBeat{} }
func (m *GW2C_HeartBeat) String() string            { return proto.CompactTextString(m) }
func (*GW2C_HeartBeat) ProtoMessage()               {}
func (*GW2C_HeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *GW2C_HeartBeat) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *GW2C_HeartBeat) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *GW2C_HeartBeat) GetTest() []string {
	if m != nil {
		return m.Test
	}
	return nil
}

// 请求开始游戏(开房间)
type C2GW_ReqStartGame struct {
	Gamekind         *int32 `protobuf:"varint,1,opt,name=gamekind" json:"gamekind,omitempty"`
	Gridnum          *int32 `protobuf:"varint,2,opt,name=gridnum" json:"gridnum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2GW_ReqStartGame) Reset()                    { *m = C2GW_ReqStartGame{} }
func (m *C2GW_ReqStartGame) String() string            { return proto.CompactTextString(m) }
func (*C2GW_ReqStartGame) ProtoMessage()               {}
func (*C2GW_ReqStartGame) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *C2GW_ReqStartGame) GetGamekind() int32 {
	if m != nil && m.Gamekind != nil {
		return *m.Gamekind
	}
	return 0
}

func (m *C2GW_ReqStartGame) GetGridnum() int32 {
	if m != nil && m.Gridnum != nil {
		return *m.Gridnum
	}
	return 0
}

type GW2C_RetStartGame struct {
	Errcode          *string `protobuf:"bytes,1,opt,name=errcode" json:"errcode,omitempty"`
	Roomid           *int64  `protobuf:"varint,2,opt,name=roomid" json:"roomid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2C_RetStartGame) Reset()                    { *m = GW2C_RetStartGame{} }
func (m *GW2C_RetStartGame) String() string            { return proto.CompactTextString(m) }
func (*GW2C_RetStartGame) ProtoMessage()               {}
func (*GW2C_RetStartGame) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *GW2C_RetStartGame) GetErrcode() string {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return ""
}

func (m *GW2C_RetStartGame) GetRoomid() int64 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

type GW2C_Ret7DayReward struct {
	Day              *uint32 `protobuf:"varint,1,opt,name=day" json:"day,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2C_Ret7DayReward) Reset()                    { *m = GW2C_Ret7DayReward{} }
func (m *GW2C_Ret7DayReward) String() string            { return proto.CompactTextString(m) }
func (*GW2C_Ret7DayReward) ProtoMessage()               {}
func (*GW2C_Ret7DayReward) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *GW2C_Ret7DayReward) GetDay() uint32 {
	if m != nil && m.Day != nil {
		return *m.Day
	}
	return 0
}

type C2GW_Get7DayReward struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2GW_Get7DayReward) Reset()                    { *m = C2GW_Get7DayReward{} }
func (m *C2GW_Get7DayReward) String() string            { return proto.CompactTextString(m) }
func (*C2GW_Get7DayReward) ProtoMessage()               {}
func (*C2GW_Get7DayReward) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func init() {
	proto.RegisterType((*C2GW_ReqLogin)(nil), "msg.C2GW_ReqLogin")
	proto.RegisterType((*GW2C_RetLogin)(nil), "msg.GW2C_RetLogin")
	proto.RegisterType((*GW2C_SendUserInfo)(nil), "msg.GW2C_SendUserInfo")
	proto.RegisterType((*GW2C_SendUserPlatformMoney)(nil), "msg.GW2C_SendUserPlatformMoney")
	proto.RegisterType((*C2GW_HeartBeat)(nil), "msg.C2GW_HeartBeat")
	proto.RegisterType((*GW2C_HeartBeat)(nil), "msg.GW2C_HeartBeat")
	proto.RegisterType((*C2GW_ReqStartGame)(nil), "msg.C2GW_ReqStartGame")
	proto.RegisterType((*GW2C_RetStartGame)(nil), "msg.GW2C_RetStartGame")
	proto.RegisterType((*GW2C_Ret7DayReward)(nil), "msg.GW2C_Ret7DayReward")
	proto.RegisterType((*C2GW_Get7DayReward)(nil), "msg.C2GW_Get7DayReward")
}

func init() { proto.RegisterFile("clientgate.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xd5, 0x92, 0x64, 0xa1, 0x93, 0xcd, 0x76, 0x6b, 0x71, 0x88, 0xca, 0x81, 0xe2, 0xd3, 0x4a,
	0x48, 0x3d, 0x44, 0x08, 0xc4, 0xb5, 0x0b, 0x0a, 0x2b, 0x81, 0x54, 0xa5, 0x42, 0x3d, 0x56, 0x26,
	0x99, 0x44, 0x56, 0x6b, 0x1b, 0xec, 0x29, 0x28, 0xfc, 0x7a, 0x94, 0x49, 0xcb, 0xd7, 0x71, 0x8f,
	0x33, 0x6f, 0xde, 0x87, 0x9f, 0xe1, 0xa6, 0x3e, 0x68, 0xb4, 0xd4, 0x29, 0xc2, 0xe5, 0x57, 0xef,
	0xc8, 0x89, 0xc8, 0x84, 0x6e, 0x3e, 0x0d, 0xe8, 0xb5, 0x3a, 0xe8, 0x9f, 0xa7, 0xad, 0x5c, 0x43,
	0x76, 0x57, 0x94, 0xdb, 0x5d, 0x85, 0xdf, 0x3e, 0xba, 0x4e, 0x5b, 0x31, 0x85, 0xc7, 0xaa, 0xae,
	0xdd, 0xd1, 0x52, 0x7e, 0xb1, 0xb8, 0xb8, 0x9d, 0x88, 0x19, 0x4c, 0xbe, 0xa3, 0xd7, 0x6d, 0xbf,
	0xc7, 0x3e, 0x7f, 0xc4, 0xab, 0x0c, 0x12, 0x72, 0x7b, 0xb4, 0x79, 0xc4, 0xe3, 0x15, 0xc4, 0xad,
	0xaa, 0x31, 0x8f, 0x87, 0x49, 0x2e, 0x20, 0x2b, 0xb7, 0xc5, 0xdd, 0xae, 0x42, 0xfa, 0xad, 0x88,
	0xde, 0xd7, 0xae, 0xc1, 0x51, 0x51, 0x1a, 0x98, 0xf1, 0xc5, 0x06, 0x6d, 0xf3, 0x39, 0xa0, 0xbf,
	0xb7, 0xad, 0x13, 0xcf, 0xe1, 0x12, 0x2d, 0x69, 0xea, 0xf9, 0x28, 0x2d, 0xa6, 0x4b, 0x13, 0xba,
	0xe5, 0x7b, 0x5e, 0xad, 0x54, 0x40, 0xf1, 0x0c, 0xe2, 0x2f, 0x2a, 0x20, 0x47, 0x48, 0x8b, 0x8c,
	0xe1, 0x81, 0xcd, 0xe0, 0x1c, 0x62, 0x4d, 0x68, 0x38, 0x50, 0x5a, 0x5c, 0x31, 0x78, 0x4f, 0x68,
	0x56, 0xda, 0xca, 0x97, 0x30, 0xff, 0xc7, 0x6e, 0x7d, 0x50, 0xd4, 0x3a, 0x6f, 0x3e, 0x39, 0x8b,
	0xfd, 0xf0, 0x96, 0xda, 0x69, 0x1b, 0xd8, 0x36, 0x91, 0x6f, 0xe1, 0x9a, 0xfb, 0xf8, 0x80, 0xca,
	0xd3, 0x0a, 0x15, 0x89, 0x14, 0xa2, 0xa3, 0x6e, 0x18, 0x8e, 0x86, 0xa7, 0x92, 0x36, 0x63, 0x88,
	0x71, 0xc2, 0x40, 0x79, 0xb4, 0x88, 0x6e, 0x27, 0x03, 0x95, 0x7d, 0x1e, 0x40, 0x7d, 0x0d, 0xb3,
	0xf3, 0x2f, 0x6c, 0x48, 0x79, 0x2a, 0x95, 0x41, 0x71, 0x03, 0x4f, 0x3a, 0x65, 0x70, 0xaf, 0xed,
	0x28, 0x91, 0x0c, 0x4d, 0x76, 0x5e, 0x37, 0xf6, 0x68, 0x58, 0x25, 0x91, 0xaf, 0x4e, 0x4d, 0x56,
	0x48, 0x7f, 0x78, 0xff, 0xf7, 0x2d, 0xae, 0xe1, 0xd2, 0x3b, 0x67, 0x74, 0x33, 0x7a, 0xcb, 0x17,
	0x20, 0xce, 0xac, 0x37, 0xef, 0x54, 0x5f, 0xe1, 0x0f, 0xe5, 0x9b, 0x21, 0x6c, 0xa3, 0xc6, 0xf6,
	0x33, 0xf9, 0x14, 0x04, 0x07, 0x2a, 0xff, 0x3e, 0xf9, 0x15, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x46,
	0xef, 0x77, 0x55, 0x02, 0x00, 0x00,
}
