// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clientlogin.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 客户端请求登陆
type C2L_ReqLogin struct {
	Account          *string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Nickname         *string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Face             *string `protobuf:"bytes,3,opt,name=face" json:"face,omitempty"`
	Token            *string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2L_ReqLogin) Reset()                    { *m = C2L_ReqLogin{} }
func (m *C2L_ReqLogin) String() string            { return proto.CompactTextString(m) }
func (*C2L_ReqLogin) ProtoMessage()               {}
func (*C2L_ReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *C2L_ReqLogin) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *C2L_ReqLogin) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *C2L_ReqLogin) GetFace() string {
	if m != nil && m.Face != nil {
		return *m.Face
	}
	return ""
}

func (m *C2L_ReqLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// 返回登陆验证结果
type L2C_RetLogin struct {
	Result           *int32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Reason           *string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	Gatehost         *IpHost `protobuf:"bytes,3,opt,name=gatehost" json:"gatehost,omitempty"`
	Verifykey        *string `protobuf:"bytes,5,opt,name=verifykey" json:"verifykey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *L2C_RetLogin) Reset()                    { *m = L2C_RetLogin{} }
func (m *L2C_RetLogin) String() string            { return proto.CompactTextString(m) }
func (*L2C_RetLogin) ProtoMessage()               {}
func (*L2C_RetLogin) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *L2C_RetLogin) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *L2C_RetLogin) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *L2C_RetLogin) GetGatehost() *IpHost {
	if m != nil {
		return m.Gatehost
	}
	return nil
}

func (m *L2C_RetLogin) GetVerifykey() string {
	if m != nil && m.Verifykey != nil {
		return *m.Verifykey
	}
	return ""
}

// 注册账户，暂时方案
type C2L_ReqRegistAccount struct {
	Account          *string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Passwd           *string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Face             *string `protobuf:"bytes,4,opt,name=face" json:"face,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2L_ReqRegistAccount) Reset()                    { *m = C2L_ReqRegistAccount{} }
func (m *C2L_ReqRegistAccount) String() string            { return proto.CompactTextString(m) }
func (*C2L_ReqRegistAccount) ProtoMessage()               {}
func (*C2L_ReqRegistAccount) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *C2L_ReqRegistAccount) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *C2L_ReqRegistAccount) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *C2L_ReqRegistAccount) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *C2L_ReqRegistAccount) GetFace() string {
	if m != nil && m.Face != nil {
		return *m.Face
	}
	return ""
}

// 注册返回
type L2C_RetRegistAccount struct {
	Account          *string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Errcode          *string `protobuf:"bytes,2,opt,name=errcode" json:"errcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *L2C_RetRegistAccount) Reset()                    { *m = L2C_RetRegistAccount{} }
func (m *L2C_RetRegistAccount) String() string            { return proto.CompactTextString(m) }
func (*L2C_RetRegistAccount) ProtoMessage()               {}
func (*L2C_RetRegistAccount) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *L2C_RetRegistAccount) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *L2C_RetRegistAccount) GetErrcode() string {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return ""
}

func init() {
	proto.RegisterType((*C2L_ReqLogin)(nil), "msg.C2L_ReqLogin")
	proto.RegisterType((*L2C_RetLogin)(nil), "msg.L2C_RetLogin")
	proto.RegisterType((*C2L_ReqRegistAccount)(nil), "msg.C2L_ReqRegistAccount")
	proto.RegisterType((*L2C_RetRegistAccount)(nil), "msg.L2C_RetRegistAccount")
}

func init() { proto.RegisterFile("clientlogin.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x99, 0x5d, 0xf7, 0xe7, 0x5d, 0xdd, 0x5c, 0xd9, 0x21, 0x08, 0x82, 0xec, 0xe4, 0xa9,
	0x87, 0x9e, 0xbc, 0xca, 0x2e, 0x0a, 0xc5, 0x43, 0xfd, 0x00, 0x33, 0xa4, 0x6f, 0x63, 0x68, 0x9b,
	0xd4, 0xe4, 0x9d, 0xb2, 0x6f, 0x2f, 0x4d, 0x0a, 0x22, 0x1e, 0x76, 0x7c, 0x1e, 0xc2, 0x2f, 0xbf,
	0xe7, 0x85, 0xad, 0x68, 0x15, 0x6a, 0x6a, 0x8d, 0x54, 0x3a, 0xeb, 0xad, 0x21, 0x93, 0x46, 0x9d,
	0x93, 0xb7, 0x49, 0x85, 0xb5, 0xd2, 0x18, 0xaa, 0xfd, 0x2b, 0x24, 0x87, 0xbc, 0x38, 0x96, 0xf8,
	0x59, 0x0c, 0x0f, 0xd3, 0x0d, 0xcc, 0xb9, 0x10, 0xe6, 0xa4, 0x89, 0x4d, 0xee, 0x27, 0x0f, 0xcb,
	0xf4, 0x06, 0x16, 0x5a, 0x89, 0x46, 0xf3, 0x0e, 0xd9, 0x95, 0x6f, 0x12, 0x98, 0xd6, 0x5c, 0x20,
	0x8b, 0x7c, 0xba, 0x86, 0x98, 0x4c, 0x83, 0x9a, 0x4d, 0x87, 0xb8, 0x7f, 0x87, 0xa4, 0xc8, 0x0f,
	0xc7, 0x12, 0x29, 0xf0, 0xd6, 0x30, 0xb3, 0xe8, 0x4e, 0x6d, 0xc0, 0xc5, 0x21, 0x73, 0x67, 0xf4,
	0x08, 0xbb, 0x83, 0x85, 0xe4, 0x84, 0x1f, 0xc6, 0x91, 0x07, 0xae, 0xf2, 0x55, 0xd6, 0x39, 0x99,
	0xbd, 0xf4, 0xcf, 0xc6, 0x51, 0xba, 0x85, 0xe5, 0x17, 0x5a, 0x55, 0x9f, 0x1b, 0x3c, 0xb3, 0xd8,
	0xff, 0xf0, 0x06, 0xbb, 0xd1, 0xb8, 0x44, 0xa9, 0x1c, 0x3d, 0x05, 0xdd, 0xff, 0xe6, 0x6b, 0x98,
	0xf5, 0xdc, 0xb9, 0xef, 0xea, 0xd7, 0xdb, 0xaf, 0x88, 0xfe, 0xac, 0x08, 0xda, 0x8f, 0xb0, 0x1b,
	0xb5, 0x2f, 0x40, 0x37, 0x30, 0x47, 0x6b, 0x85, 0xa9, 0xc6, 0x6b, 0xfc, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xdc, 0xea, 0x6a, 0x30, 0x67, 0x01, 0x00, 0x00,
}
