// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateroom.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// room 注册到GW
type RS2GW_ReqRegist struct {
	Account          *string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Passwd           *string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	Agentname        *string `protobuf:"bytes,3,opt,name=agentname" json:"agentname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RS2GW_ReqRegist) Reset()                    { *m = RS2GW_ReqRegist{} }
func (m *RS2GW_ReqRegist) String() string            { return proto.CompactTextString(m) }
func (*RS2GW_ReqRegist) ProtoMessage()               {}
func (*RS2GW_ReqRegist) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *RS2GW_ReqRegist) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *RS2GW_ReqRegist) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *RS2GW_ReqRegist) GetAgentname() string {
	if m != nil && m.Agentname != nil {
		return *m.Agentname
	}
	return ""
}

// 注册返回
type GW2RS_RetRegist struct {
	Errcode          *string `protobuf:"bytes,1,opt,name=errcode" json:"errcode,omitempty"`
	Agentname        *string `protobuf:"bytes,2,opt,name=agentname" json:"agentname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2RS_RetRegist) Reset()                    { *m = GW2RS_RetRegist{} }
func (m *GW2RS_RetRegist) String() string            { return proto.CompactTextString(m) }
func (*GW2RS_RetRegist) ProtoMessage()               {}
func (*GW2RS_RetRegist) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *GW2RS_RetRegist) GetErrcode() string {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return ""
}

func (m *GW2RS_RetRegist) GetAgentname() string {
	if m != nil && m.Agentname != nil {
		return *m.Agentname
	}
	return ""
}

// 通知RS玩家断开连接清理房间
type GW2RS_UserDisconnect struct {
	Roomid           *int64  `protobuf:"varint,1,opt,name=roomid" json:"roomid,omitempty"`
	Userid           *uint64 `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2RS_UserDisconnect) Reset()                    { *m = GW2RS_UserDisconnect{} }
func (m *GW2RS_UserDisconnect) String() string            { return proto.CompactTextString(m) }
func (*GW2RS_UserDisconnect) ProtoMessage()               {}
func (*GW2RS_UserDisconnect) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *GW2RS_UserDisconnect) GetRoomid() int64 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *GW2RS_UserDisconnect) GetUserid() uint64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

// 通知RS玩家断开连接清理房间,返回
type RS2GW_RetUserDisconnect struct {
	Roomid           *int64  `protobuf:"varint,1,opt,name=roomid" json:"roomid,omitempty"`
	Userid           *uint64 `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
	Errcode          *string `protobuf:"bytes,3,opt,name=errcode" json:"errcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RS2GW_RetUserDisconnect) Reset()                    { *m = RS2GW_RetUserDisconnect{} }
func (m *RS2GW_RetUserDisconnect) String() string            { return proto.CompactTextString(m) }
func (*RS2GW_RetUserDisconnect) ProtoMessage()               {}
func (*RS2GW_RetUserDisconnect) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *RS2GW_RetUserDisconnect) GetRoomid() int64 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *RS2GW_RetUserDisconnect) GetUserid() uint64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *RS2GW_RetUserDisconnect) GetErrcode() string {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return ""
}

func init() {
	proto.RegisterType((*RS2GW_ReqRegist)(nil), "msg.RS2GW_ReqRegist")
	proto.RegisterType((*GW2RS_RetRegist)(nil), "msg.GW2RS_RetRegist")
	proto.RegisterType((*GW2RS_UserDisconnect)(nil), "msg.GW2RS_UserDisconnect")
	proto.RegisterType((*RS2GW_RetUserDisconnect)(nil), "msg.RS2GW_RetUserDisconnect")
}

func init() { proto.RegisterFile("gateroom.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8e, 0x41, 0x8b, 0xc2, 0x30,
	0x10, 0x46, 0xe9, 0x76, 0xd9, 0xa5, 0x73, 0x68, 0xd9, 0xb2, 0x60, 0x8f, 0x92, 0x93, 0x27, 0x0f,
	0x05, 0xfd, 0x05, 0x4a, 0xc1, 0x63, 0x8a, 0xf4, 0x58, 0x42, 0x3a, 0x84, 0x1c, 0x9a, 0xd4, 0x64,
	0x8a, 0x7f, 0x5f, 0x92, 0x2a, 0xea, 0xd1, 0xe3, 0x37, 0xf0, 0xde, 0x3c, 0xc8, 0x95, 0x20, 0x74,
	0xd6, 0x8e, 0xdb, 0xc9, 0x59, 0xb2, 0x65, 0x3a, 0x7a, 0xc5, 0x8e, 0x50, 0xf0, 0xb6, 0x6e, 0xba,
	0x9e, 0xe3, 0x85, 0xa3, 0xd2, 0x9e, 0xca, 0x02, 0x7e, 0x85, 0x94, 0x76, 0x36, 0x54, 0x25, 0xeb,
	0x64, 0x93, 0x95, 0x39, 0xfc, 0x4c, 0xc2, 0xfb, 0xeb, 0x50, 0x7d, 0xc5, 0xfd, 0x07, 0x99, 0x50,
	0x68, 0xc8, 0x88, 0x11, 0xab, 0x34, 0x9c, 0xd8, 0x0e, 0x8a, 0xa6, 0xab, 0x79, 0xdb, 0x73, 0xa4,
	0xa7, 0x06, 0x9d, 0x93, 0x76, 0xc0, 0xbb, 0xe6, 0x0d, 0x8b, 0x26, 0xb6, 0x87, 0xff, 0x05, 0x3b,
	0x7b, 0x74, 0x07, 0xed, 0xa5, 0x35, 0x06, 0x25, 0x85, 0x8f, 0x21, 0x54, 0x0f, 0x11, 0x4d, 0xc3,
	0x9e, 0x3d, 0x3a, 0xbd, 0x14, 0x7c, 0xb3, 0x13, 0xac, 0x1e, 0xd5, 0xf4, 0x19, 0xfa, 0x9a, 0x15,
	0xd3, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x94, 0x72, 0xac, 0x87, 0x17, 0x01, 0x00, 0x00,
}
