// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 购买道具
type C2GW_BuyItem struct {
	Productid        *uint32 `protobuf:"varint,1,opt,name=productid" json:"productid,omitempty"`
	Num              *uint32 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GW_BuyItem) Reset()                    { *m = C2GW_BuyItem{} }
func (m *C2GW_BuyItem) String() string            { return proto.CompactTextString(m) }
func (*C2GW_BuyItem) ProtoMessage()               {}
func (*C2GW_BuyItem) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *C2GW_BuyItem) GetProductid() uint32 {
	if m != nil && m.Productid != nil {
		return *m.Productid
	}
	return 0
}

func (m *C2GW_BuyItem) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 更新背包添加
type GW2C_AddPackageItem struct {
	Itemid           *uint32 `protobuf:"varint,1,opt,name=itemid" json:"itemid,omitempty"`
	Num              *uint32 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2C_AddPackageItem) Reset()                    { *m = GW2C_AddPackageItem{} }
func (m *GW2C_AddPackageItem) String() string            { return proto.CompactTextString(m) }
func (*GW2C_AddPackageItem) ProtoMessage()               {}
func (*GW2C_AddPackageItem) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *GW2C_AddPackageItem) GetItemid() uint32 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

func (m *GW2C_AddPackageItem) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 更新背包扣除
type GW2C_RemovePackageItem struct {
	Itemid           *uint32 `protobuf:"varint,1,opt,name=itemid" json:"itemid,omitempty"`
	Num              *uint32 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2C_RemovePackageItem) Reset()                    { *m = GW2C_RemovePackageItem{} }
func (m *GW2C_RemovePackageItem) String() string            { return proto.CompactTextString(m) }
func (*GW2C_RemovePackageItem) ProtoMessage()               {}
func (*GW2C_RemovePackageItem) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *GW2C_RemovePackageItem) GetItemid() uint32 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

func (m *GW2C_RemovePackageItem) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 更新元宝
type GW2C_UpdateYuanbao struct {
	Num              *uint32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2C_UpdateYuanbao) Reset()                    { *m = GW2C_UpdateYuanbao{} }
func (m *GW2C_UpdateYuanbao) String() string            { return proto.CompactTextString(m) }
func (*GW2C_UpdateYuanbao) ProtoMessage()               {}
func (*GW2C_UpdateYuanbao) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *GW2C_UpdateYuanbao) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 更新点卷
type GW2C_UpdateCoupon struct {
	Num              *uint32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2C_UpdateCoupon) Reset()                    { *m = GW2C_UpdateCoupon{} }
func (m *GW2C_UpdateCoupon) String() string            { return proto.CompactTextString(m) }
func (*GW2C_UpdateCoupon) ProtoMessage()               {}
func (*GW2C_UpdateCoupon) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

func (m *GW2C_UpdateCoupon) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 更新免费步数
type GW2C_UpdateFreeStep struct {
	Num              *int32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GW2C_UpdateFreeStep) Reset()                    { *m = GW2C_UpdateFreeStep{} }
func (m *GW2C_UpdateFreeStep) String() string            { return proto.CompactTextString(m) }
func (*GW2C_UpdateFreeStep) ProtoMessage()               {}
func (*GW2C_UpdateFreeStep) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{5} }

func (m *GW2C_UpdateFreeStep) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 货物信息
type DeliveryGoods struct {
	Itemid           *uint32 `protobuf:"varint,1,opt,name=itemid" json:"itemid,omitempty"`
	Num              *uint32 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeliveryGoods) Reset()                    { *m = DeliveryGoods{} }
func (m *DeliveryGoods) String() string            { return proto.CompactTextString(m) }
func (*DeliveryGoods) ProtoMessage()               {}
func (*DeliveryGoods) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{6} }

func (m *DeliveryGoods) GetItemid() uint32 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

func (m *DeliveryGoods) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 请求提货
type C2GW_ReqDeliveryGoods struct {
	List             []*DeliveryGoods `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Token            *string          `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *C2GW_ReqDeliveryGoods) Reset()                    { *m = C2GW_ReqDeliveryGoods{} }
func (m *C2GW_ReqDeliveryGoods) String() string            { return proto.CompactTextString(m) }
func (*C2GW_ReqDeliveryGoods) ProtoMessage()               {}
func (*C2GW_ReqDeliveryGoods) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{7} }

func (m *C2GW_ReqDeliveryGoods) GetList() []*DeliveryGoods {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *C2GW_ReqDeliveryGoods) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// 提取钻石
type C2GW_ReqDeliveryDiamond struct {
	List             []*DeliveryGoods `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Token            *string          `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *C2GW_ReqDeliveryDiamond) Reset()                    { *m = C2GW_ReqDeliveryDiamond{} }
func (m *C2GW_ReqDeliveryDiamond) String() string            { return proto.CompactTextString(m) }
func (*C2GW_ReqDeliveryDiamond) ProtoMessage()               {}
func (*C2GW_ReqDeliveryDiamond) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{8} }

func (m *C2GW_ReqDeliveryDiamond) GetList() []*DeliveryGoods {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *C2GW_ReqDeliveryDiamond) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type GW2C_RetDeliveryDiamond struct {
	Diamond          *int32 `protobuf:"varint,1,opt,name=diamond" json:"diamond,omitempty"`
	Diamondparts     *int32 `protobuf:"varint,2,opt,name=diamondparts" json:"diamondparts,omitempty"`
	Total            *int32 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GW2C_RetDeliveryDiamond) Reset()                    { *m = GW2C_RetDeliveryDiamond{} }
func (m *GW2C_RetDeliveryDiamond) String() string            { return proto.CompactTextString(m) }
func (*GW2C_RetDeliveryDiamond) ProtoMessage()               {}
func (*GW2C_RetDeliveryDiamond) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{9} }

func (m *GW2C_RetDeliveryDiamond) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *GW2C_RetDeliveryDiamond) GetDiamondparts() int32 {
	if m != nil && m.Diamondparts != nil {
		return *m.Diamondparts
	}
	return 0
}

func (m *GW2C_RetDeliveryDiamond) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

type BigRewardItem struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Num              *uint32 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BigRewardItem) Reset()                    { *m = BigRewardItem{} }
func (m *BigRewardItem) String() string            { return proto.CompactTextString(m) }
func (*BigRewardItem) ProtoMessage()               {}
func (*BigRewardItem) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{10} }

func (m *BigRewardItem) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BigRewardItem) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 全服大奖被拿走次数
type Sync_BigRewardPickNum struct {
	List             []*BigRewardItem `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Sync_BigRewardPickNum) Reset()                    { *m = Sync_BigRewardPickNum{} }
func (m *Sync_BigRewardPickNum) String() string            { return proto.CompactTextString(m) }
func (*Sync_BigRewardPickNum) ProtoMessage()               {}
func (*Sync_BigRewardPickNum) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{11} }

func (m *Sync_BigRewardPickNum) GetList() []*BigRewardItem {
	if m != nil {
		return m.List
	}
	return nil
}

// 使用道具
type C2GW_UseBagItem struct {
	Itemid           *uint32 `protobuf:"varint,1,opt,name=itemid" json:"itemid,omitempty"`
	Num              *uint32 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GW_UseBagItem) Reset()                    { *m = C2GW_UseBagItem{} }
func (m *C2GW_UseBagItem) String() string            { return proto.CompactTextString(m) }
func (*C2GW_UseBagItem) ProtoMessage()               {}
func (*C2GW_UseBagItem) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{12} }

func (m *C2GW_UseBagItem) GetItemid() uint32 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

func (m *C2GW_UseBagItem) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 出售道具
type C2GW_SellBagItem struct {
	List             []*PairNumItem `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *C2GW_SellBagItem) Reset()                    { *m = C2GW_SellBagItem{} }
func (m *C2GW_SellBagItem) String() string            { return proto.CompactTextString(m) }
func (*C2GW_SellBagItem) ProtoMessage()               {}
func (*C2GW_SellBagItem) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{13} }

func (m *C2GW_SellBagItem) GetList() []*PairNumItem {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*C2GW_BuyItem)(nil), "msg.C2GW_BuyItem")
	proto.RegisterType((*GW2C_AddPackageItem)(nil), "msg.GW2C_AddPackageItem")
	proto.RegisterType((*GW2C_RemovePackageItem)(nil), "msg.GW2C_RemovePackageItem")
	proto.RegisterType((*GW2C_UpdateYuanbao)(nil), "msg.GW2C_UpdateYuanbao")
	proto.RegisterType((*GW2C_UpdateCoupon)(nil), "msg.GW2C_UpdateCoupon")
	proto.RegisterType((*GW2C_UpdateFreeStep)(nil), "msg.GW2C_UpdateFreeStep")
	proto.RegisterType((*DeliveryGoods)(nil), "msg.DeliveryGoods")
	proto.RegisterType((*C2GW_ReqDeliveryGoods)(nil), "msg.C2GW_ReqDeliveryGoods")
	proto.RegisterType((*C2GW_ReqDeliveryDiamond)(nil), "msg.C2GW_ReqDeliveryDiamond")
	proto.RegisterType((*GW2C_RetDeliveryDiamond)(nil), "msg.GW2C_RetDeliveryDiamond")
	proto.RegisterType((*BigRewardItem)(nil), "msg.BigRewardItem")
	proto.RegisterType((*Sync_BigRewardPickNum)(nil), "msg.Sync_BigRewardPickNum")
	proto.RegisterType((*C2GW_UseBagItem)(nil), "msg.C2GW_UseBagItem")
	proto.RegisterType((*C2GW_SellBagItem)(nil), "msg.C2GW_SellBagItem")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4f, 0xea, 0x40,
	0x14, 0xc5, 0x03, 0x7d, 0xbc, 0x17, 0x2e, 0xf4, 0x01, 0x55, 0xa4, 0x71, 0x61, 0x6a, 0x57, 0x2c,
	0x4c, 0x17, 0x4d, 0x5c, 0xb8, 0x14, 0x88, 0xa8, 0x0b, 0x24, 0x10, 0x42, 0x5c, 0x91, 0xb1, 0x73,
	0x6d, 0x26, 0x74, 0x3a, 0xb5, 0x9d, 0xc1, 0xf0, 0xed, 0x0d, 0x53, 0x30, 0x94, 0x10, 0xff, 0xec,
	0xda, 0x3b, 0xbf, 0x73, 0xee, 0xbd, 0x67, 0x06, 0x80, 0x49, 0xe4, 0x5e, 0x92, 0x0a, 0x29, 0x2c,
	0x83, 0x67, 0xe1, 0x79, 0x9d, 0xe2, 0x2b, 0x8b, 0x31, 0x2f, 0xb9, 0x1e, 0xd4, 0xfb, 0xfe, 0x70,
	0xbe, 0xe8, 0xa9, 0xf5, 0x83, 0x44, 0x6e, 0xb5, 0xa0, 0x9a, 0xa4, 0x82, 0xaa, 0x40, 0x32, 0x6a,
	0x97, 0x9c, 0x52, 0xd7, 0xb4, 0x6a, 0x60, 0xc4, 0x8a, 0xdb, 0xe5, 0xcd, 0x8f, 0xeb, 0xc3, 0xc9,
	0x70, 0xee, 0xf7, 0x17, 0xb7, 0x94, 0x8e, 0x49, 0xb0, 0x24, 0x21, 0x6a, 0xd9, 0x7f, 0xf8, 0xbb,
	0xe9, 0x73, 0x5c, 0x73, 0x0d, 0x67, 0x5a, 0x33, 0x41, 0x2e, 0x56, 0xf8, 0x63, 0xd9, 0x25, 0x58,
	0x5a, 0x36, 0x4b, 0x28, 0x91, 0xf8, 0xac, 0x48, 0xfc, 0x42, 0xc4, 0x0e, 0xd1, 0xbc, 0xeb, 0x40,
	0x6b, 0x0f, 0xe9, 0x0b, 0x95, 0x88, 0xb8, 0x48, 0xb8, 0xdb, 0x79, 0x73, 0xe2, 0x2e, 0x45, 0x9c,
	0x4a, 0x4c, 0xf6, 0x99, 0x8a, 0x7b, 0x05, 0xe6, 0x00, 0x23, 0xb6, 0xc2, 0x74, 0x3d, 0x14, 0x82,
	0x66, 0x5f, 0x8f, 0x75, 0x0f, 0x6d, 0x9d, 0xd8, 0x04, 0xdf, 0x8a, 0x2a, 0x07, 0xfe, 0x44, 0x2c,
	0x93, 0x76, 0xc9, 0x31, 0xba, 0x35, 0xdf, 0xf2, 0x78, 0x16, 0x7a, 0x45, 0xc2, 0x84, 0x8a, 0x14,
	0x4b, 0x8c, 0xb5, 0x53, 0xd5, 0x7d, 0x84, 0xce, 0xa1, 0xd3, 0x80, 0x11, 0x2e, 0x62, 0xfa, 0x7b,
	0xaf, 0x27, 0xe8, 0x6c, 0x33, 0x96, 0x87, 0x5e, 0x0d, 0xf8, 0x47, 0xf3, 0xcf, 0x7c, 0x5f, 0xeb,
	0x14, 0xea, 0xdb, 0x42, 0x42, 0x52, 0x99, 0x69, 0x87, 0x4a, 0x6e, 0x28, 0x49, 0x64, 0x1b, 0x3a,
	0x94, 0x2e, 0x98, 0x3d, 0x16, 0x4e, 0xf0, 0x9d, 0xa4, 0x54, 0xdf, 0x15, 0x40, 0xf9, 0x78, 0x20,
	0x37, 0xd0, 0x9e, 0xae, 0xe3, 0x60, 0xf1, 0x89, 0x8f, 0x59, 0xb0, 0x1c, 0x29, 0x7e, 0x74, 0x89,
	0x82, 0xa7, 0xeb, 0x41, 0x43, 0x27, 0x30, 0xcb, 0xb0, 0x47, 0xc2, 0xef, 0x9f, 0x84, 0x0f, 0x4d,
	0xcd, 0x4f, 0x31, 0x8a, 0x76, 0x82, 0x8b, 0x42, 0x97, 0xa6, 0xee, 0x32, 0x26, 0x2c, 0x1d, 0x29,
	0xbe, 0x39, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0x45, 0xac, 0x46, 0x05, 0x01, 0x03, 0x00, 0x00,
}
