// Code generated by protoc-gen-go. DO NOT EDIT.
// source: matchroom.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// room请求注册到match
type RS2MS_ReqRegist struct {
	Account          *string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Passwd           *string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RS2MS_ReqRegist) Reset()                    { *m = RS2MS_ReqRegist{} }
func (m *RS2MS_ReqRegist) String() string            { return proto.CompactTextString(m) }
func (*RS2MS_ReqRegist) ProtoMessage()               {}
func (*RS2MS_ReqRegist) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *RS2MS_ReqRegist) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *RS2MS_ReqRegist) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *RS2MS_ReqRegist) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

// 注册返回
type MS2RS_RetRegist struct {
	Errcode          *string `protobuf:"bytes,1,opt,name=errcode" json:"errcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MS2RS_RetRegist) Reset()                    { *m = MS2RS_RetRegist{} }
func (m *MS2RS_RetRegist) String() string            { return proto.CompactTextString(m) }
func (*MS2RS_RetRegist) ProtoMessage()               {}
func (*MS2RS_RetRegist) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *MS2RS_RetRegist) GetErrcode() string {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return ""
}

// 心跳
type RS2MS_HeartBeat struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RS2MS_HeartBeat) Reset()                    { *m = RS2MS_HeartBeat{} }
func (m *RS2MS_HeartBeat) String() string            { return proto.CompactTextString(m) }
func (*RS2MS_HeartBeat) ProtoMessage()               {}
func (*RS2MS_HeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

//
type MS2RS_HeartBeat struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MS2RS_HeartBeat) Reset()                    { *m = MS2RS_HeartBeat{} }
func (m *MS2RS_HeartBeat) String() string            { return proto.CompactTextString(m) }
func (*MS2RS_HeartBeat) ProtoMessage()               {}
func (*MS2RS_HeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

// 发送Gate信息给Room
type GateSimpleInfo struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Host             *IpHost `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GateSimpleInfo) Reset()                    { *m = GateSimpleInfo{} }
func (m *GateSimpleInfo) String() string            { return proto.CompactTextString(m) }
func (*GateSimpleInfo) ProtoMessage()               {}
func (*GateSimpleInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{4} }

func (m *GateSimpleInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GateSimpleInfo) GetHost() *IpHost {
	if m != nil {
		return m.Host
	}
	return nil
}

type MS2RS_GateInfo struct {
	Gates            []*GateSimpleInfo `protobuf:"bytes,1,rep,name=gates" json:"gates,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MS2RS_GateInfo) Reset()                    { *m = MS2RS_GateInfo{} }
func (m *MS2RS_GateInfo) String() string            { return proto.CompactTextString(m) }
func (*MS2RS_GateInfo) ProtoMessage()               {}
func (*MS2RS_GateInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{5} }

func (m *MS2RS_GateInfo) GetGates() []*GateSimpleInfo {
	if m != nil {
		return m.Gates
	}
	return nil
}

// 通知Room创建游戏房间
type MS2RS_CreateRoom struct {
	Userid           *uint64 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Roomid           *int64  `protobuf:"varint,2,opt,name=roomid" json:"roomid,omitempty"`
	Gamekind         *int32  `protobuf:"varint,3,opt,name=gamekind" json:"gamekind,omitempty"`
	Gridnum          *int32  `protobuf:"varint,4,opt,name=gridnum" json:"gridnum,omitempty"`
	Sidgate          *int32  `protobuf:"varint,5,opt,name=sidgate" json:"sidgate,omitempty"`
	Quotaflag        *bool   `protobuf:"varint,6,opt,name=quotaflag" json:"quotaflag,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MS2RS_CreateRoom) Reset()                    { *m = MS2RS_CreateRoom{} }
func (m *MS2RS_CreateRoom) String() string            { return proto.CompactTextString(m) }
func (*MS2RS_CreateRoom) ProtoMessage()               {}
func (*MS2RS_CreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{6} }

func (m *MS2RS_CreateRoom) GetUserid() uint64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *MS2RS_CreateRoom) GetRoomid() int64 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *MS2RS_CreateRoom) GetGamekind() int32 {
	if m != nil && m.Gamekind != nil {
		return *m.Gamekind
	}
	return 0
}

func (m *MS2RS_CreateRoom) GetGridnum() int32 {
	if m != nil && m.Gridnum != nil {
		return *m.Gridnum
	}
	return 0
}

func (m *MS2RS_CreateRoom) GetSidgate() int32 {
	if m != nil && m.Sidgate != nil {
		return *m.Sidgate
	}
	return 0
}

func (m *MS2RS_CreateRoom) GetQuotaflag() bool {
	if m != nil && m.Quotaflag != nil {
		return *m.Quotaflag
	}
	return false
}

// 创建返回
type RS2MS_RetCreateRoom struct {
	Roomid           *int64  `protobuf:"varint,1,opt,name=roomid" json:"roomid,omitempty"`
	Userid           *uint64 `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
	Sidgate          *int32  `protobuf:"varint,3,opt,name=sidgate" json:"sidgate,omitempty"`
	Errcode          *string `protobuf:"bytes,4,opt,name=errcode" json:"errcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RS2MS_RetCreateRoom) Reset()                    { *m = RS2MS_RetCreateRoom{} }
func (m *RS2MS_RetCreateRoom) String() string            { return proto.CompactTextString(m) }
func (*RS2MS_RetCreateRoom) ProtoMessage()               {}
func (*RS2MS_RetCreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{7} }

func (m *RS2MS_RetCreateRoom) GetRoomid() int64 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *RS2MS_RetCreateRoom) GetUserid() uint64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *RS2MS_RetCreateRoom) GetSidgate() int32 {
	if m != nil && m.Sidgate != nil {
		return *m.Sidgate
	}
	return 0
}

func (m *RS2MS_RetCreateRoom) GetErrcode() string {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return ""
}

// 通知删除房间
type RS2MS_DeleteRoom struct {
	Roomid           *int64 `protobuf:"varint,1,opt,name=roomid" json:"roomid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RS2MS_DeleteRoom) Reset()                    { *m = RS2MS_DeleteRoom{} }
func (m *RS2MS_DeleteRoom) String() string            { return proto.CompactTextString(m) }
func (*RS2MS_DeleteRoom) ProtoMessage()               {}
func (*RS2MS_DeleteRoom) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{8} }

func (m *RS2MS_DeleteRoom) GetRoomid() int64 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

// 通知更新奖池
type RS2MS_UpdateRewardPool struct {
	Mapid            *int32 `protobuf:"varint,1,opt,name=mapid" json:"mapid,omitempty"`
	Cost             *int32 `protobuf:"varint,2,opt,name=cost" json:"cost,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RS2MS_UpdateRewardPool) Reset()                    { *m = RS2MS_UpdateRewardPool{} }
func (m *RS2MS_UpdateRewardPool) String() string            { return proto.CompactTextString(m) }
func (*RS2MS_UpdateRewardPool) ProtoMessage()               {}
func (*RS2MS_UpdateRewardPool) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{9} }

func (m *RS2MS_UpdateRewardPool) GetMapid() int32 {
	if m != nil && m.Mapid != nil {
		return *m.Mapid
	}
	return 0
}

func (m *RS2MS_UpdateRewardPool) GetCost() int32 {
	if m != nil && m.Cost != nil {
		return *m.Cost
	}
	return 0
}

func init() {
	proto.RegisterType((*RS2MS_ReqRegist)(nil), "msg.RS2MS_ReqRegist")
	proto.RegisterType((*MS2RS_RetRegist)(nil), "msg.MS2RS_RetRegist")
	proto.RegisterType((*RS2MS_HeartBeat)(nil), "msg.RS2MS_HeartBeat")
	proto.RegisterType((*MS2RS_HeartBeat)(nil), "msg.MS2RS_HeartBeat")
	proto.RegisterType((*GateSimpleInfo)(nil), "msg.GateSimpleInfo")
	proto.RegisterType((*MS2RS_GateInfo)(nil), "msg.MS2RS_GateInfo")
	proto.RegisterType((*MS2RS_CreateRoom)(nil), "msg.MS2RS_CreateRoom")
	proto.RegisterType((*RS2MS_RetCreateRoom)(nil), "msg.RS2MS_RetCreateRoom")
	proto.RegisterType((*RS2MS_DeleteRoom)(nil), "msg.RS2MS_DeleteRoom")
	proto.RegisterType((*RS2MS_UpdateRewardPool)(nil), "msg.RS2MS_UpdateRewardPool")
}

func init() { proto.RegisterFile("matchroom.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0xeb, 0xda, 0x30,
	0x14, 0xc7, 0xa9, 0x6d, 0x9d, 0x3e, 0x9d, 0xd5, 0x0a, 0xa3, 0xdb, 0x49, 0x72, 0xf2, 0xe4, 0xa1,
	0x6c, 0x87, 0xdd, 0xc6, 0x36, 0x98, 0x1e, 0x84, 0xd1, 0x32, 0x76, 0x1c, 0xa1, 0x79, 0xd6, 0xb0,
	0xa6, 0xa9, 0x49, 0x8a, 0xec, 0xbf, 0x1f, 0x49, 0xac, 0xfe, 0x84, 0xdf, 0x31, 0x8f, 0xf7, 0x3e,
	0x9f, 0xf7, 0xbe, 0x81, 0x44, 0x50, 0x53, 0x9d, 0x95, 0x94, 0x62, 0xd7, 0x29, 0x69, 0x64, 0x1a,
	0x0a, 0x5d, 0x7f, 0x98, 0x33, 0x3c, 0xf1, 0x16, 0x7d, 0x89, 0x7c, 0x81, 0xa4, 0x28, 0xf3, 0x63,
	0xf9, 0xa7, 0xc0, 0x4b, 0x81, 0x35, 0xd7, 0x26, 0x4d, 0xe0, 0x0d, 0xad, 0x2a, 0xd9, 0xb7, 0x26,
	0x0b, 0x36, 0xc1, 0x76, 0x9a, 0x2e, 0x60, 0xdc, 0x51, 0xad, 0xaf, 0x2c, 0x1b, 0xb9, 0xf7, 0x1c,
	0xa2, 0x96, 0x0a, 0xcc, 0x42, 0xfb, 0x22, 0x04, 0x92, 0x63, 0x99, 0x17, 0x96, 0x60, 0x1e, 0x04,
	0x54, 0xaa, 0x92, 0x0c, 0x3d, 0x81, 0xac, 0x06, 0xcb, 0x1e, 0xa9, 0x32, 0x5f, 0x91, 0x1a, 0x5b,
	0xf2, 0x63, 0x8f, 0xd2, 0x67, 0x58, 0xfc, 0xa0, 0x06, 0x4b, 0x2e, 0xba, 0x06, 0x0f, 0xed, 0x49,
	0xde, 0x4d, 0x7e, 0x8f, 0xf7, 0x10, 0x9d, 0xa5, 0x36, 0x6e, 0x8b, 0x59, 0x3e, 0xdb, 0x09, 0x5d,
	0xef, 0x0e, 0xdd, 0x5e, 0x6a, 0x43, 0x3e, 0xc2, 0xc2, 0xd3, 0x2c, 0xc0, 0x8d, 0x12, 0x88, 0x6b,
	0x6a, 0x50, 0x67, 0xc1, 0x26, 0xdc, 0xce, 0xf2, 0xb5, 0xeb, 0x7e, 0xc6, 0x93, 0x7f, 0xb0, 0xf4,
	0x53, 0xdf, 0x14, 0x52, 0x83, 0x85, 0x94, 0xc2, 0x1e, 0xdb, 0x6b, 0x54, 0x9c, 0x39, 0x69, 0x64,
	0xdf, 0x36, 0x41, 0xee, 0x8f, 0x0f, 0xd3, 0x25, 0x4c, 0x6a, 0x2a, 0xf0, 0x2f, 0x6f, 0x99, 0x0b,
	0x20, 0xb6, 0xd7, 0xd6, 0x8a, 0xb3, 0xb6, 0x17, 0x59, 0x34, 0x14, 0x34, 0x67, 0xd6, 0x9e, 0xc5,
	0xae, 0xb0, 0x82, 0xe9, 0xa5, 0x97, 0x86, 0x9e, 0x1a, 0x5a, 0x67, 0xe3, 0x4d, 0xb0, 0x9d, 0x90,
	0xdf, 0xb0, 0x1e, 0x72, 0x37, 0xcf, 0xf6, 0x9b, 0x2d, 0x70, 0xb6, 0xc7, 0x36, 0x23, 0xb7, 0xcd,
	0x0b, 0xf4, 0x5d, 0x3e, 0x44, 0x1d, 0xdd, 0xbe, 0x63, 0xe9, 0xc1, 0xdf, 0xb1, 0xc1, 0xd7, 0xa9,
	0xe4, 0x13, 0xbc, 0xf3, 0x3d, 0xbf, 0x3a, 0x66, 0xcd, 0x78, 0xa5, 0x8a, 0xfd, 0x94, 0xb2, 0x49,
	0xdf, 0x42, 0x2c, 0x68, 0x77, 0x6b, 0x8c, 0x6d, 0xfe, 0xd5, 0x90, 0x78, 0xfc, 0x3f, 0x00, 0x00,
	0xff, 0xff, 0x45, 0x76, 0xb7, 0x68, 0x50, 0x02, 0x00, 0x00,
}
