// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serialize.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 道具位置
type ItemPos int32

const (
	ItemPos_Bag     ItemPos = 0
	ItemPos_Storage ItemPos = 1
)

var ItemPos_name = map[int32]string{
	0: "Bag",
	1: "Storage",
}
var ItemPos_value = map[string]int32{
	"Bag":     0,
	"Storage": 1,
}

func (x ItemPos) Enum() *ItemPos {
	p := new(ItemPos)
	*p = x
	return p
}
func (x ItemPos) String() string {
	return proto.EnumName(ItemPos_name, int32(x))
}
func (x *ItemPos) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ItemPos_value, data, "ItemPos")
	if err != nil {
		return err
	}
	*x = ItemPos(value)
	return nil
}
func (ItemPos) EnumDescriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

type EntityBase struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Face             *string `protobuf:"bytes,3,opt,name=face" json:"face,omitempty"`
	Sex              *int32  `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
	Account          *string `protobuf:"bytes,5,opt,name=account" json:"account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EntityBase) Reset()                    { *m = EntityBase{} }
func (m *EntityBase) String() string            { return proto.CompactTextString(m) }
func (*EntityBase) ProtoMessage()               {}
func (*EntityBase) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

func (m *EntityBase) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *EntityBase) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *EntityBase) GetFace() string {
	if m != nil && m.Face != nil {
		return *m.Face
	}
	return ""
}

func (m *EntityBase) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *EntityBase) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

type SimpleCounter struct {
	Freestep          *int32 `protobuf:"varint,1,opt,name=freestep" json:"freestep,omitempty"`
	Givestep          *int64 `protobuf:"varint,2,opt,name=givestep" json:"givestep,omitempty"`
	DiamondRoomCost   *int64 `protobuf:"varint,3,opt,name=diamond_room_cost" json:"diamond_room_cost,omitempty"`
	DiamondRoomIncome *int64 `protobuf:"varint,4,opt,name=diamond_room_income" json:"diamond_room_income,omitempty"`
	DiamondRoomStep   *int64 `protobuf:"varint,5,opt,name=diamond_room_step" json:"diamond_room_step,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *SimpleCounter) Reset()                    { *m = SimpleCounter{} }
func (m *SimpleCounter) String() string            { return proto.CompactTextString(m) }
func (*SimpleCounter) ProtoMessage()               {}
func (*SimpleCounter) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

func (m *SimpleCounter) GetFreestep() int32 {
	if m != nil && m.Freestep != nil {
		return *m.Freestep
	}
	return 0
}

func (m *SimpleCounter) GetGivestep() int64 {
	if m != nil && m.Givestep != nil {
		return *m.Givestep
	}
	return 0
}

func (m *SimpleCounter) GetDiamondRoomCost() int64 {
	if m != nil && m.DiamondRoomCost != nil {
		return *m.DiamondRoomCost
	}
	return 0
}

func (m *SimpleCounter) GetDiamondRoomIncome() int64 {
	if m != nil && m.DiamondRoomIncome != nil {
		return *m.DiamondRoomIncome
	}
	return 0
}

func (m *SimpleCounter) GetDiamondRoomStep() int64 {
	if m != nil && m.DiamondRoomStep != nil {
		return *m.DiamondRoomStep
	}
	return 0
}

type UserBase struct {
	Level            *uint32        `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Exp              *uint32        `protobuf:"varint,2,opt,name=exp" json:"exp,omitempty"`
	Money            *uint32        `protobuf:"varint,3,opt,name=money" json:"money,omitempty"`
	Coupon           *uint32        `protobuf:"varint,4,opt,name=coupon" json:"coupon,omitempty"`
	Yuanbao          *uint32        `protobuf:"varint,5,opt,name=yuanbao" json:"yuanbao,omitempty"`
	Tmlogin          *int64         `protobuf:"varint,6,opt,name=tmlogin" json:"tmlogin,omitempty"`
	Tmlogout         *int64         `protobuf:"varint,7,opt,name=tmlogout" json:"tmlogout,omitempty"`
	Continuelogin    *uint32        `protobuf:"varint,8,opt,name=continuelogin" json:"continuelogin,omitempty"`
	Nocountlogin     *uint32        `protobuf:"varint,9,opt,name=nocountlogin" json:"nocountlogin,omitempty"`
	Signreward       *uint32        `protobuf:"varint,10,opt,name=signreward" json:"signreward,omitempty"`
	Signtime         *uint32        `protobuf:"varint,11,opt,name=signtime" json:"signtime,omitempty"`
	Addrlist         []*UserAddress `protobuf:"bytes,12,rep,name=addrlist" json:"addrlist,omitempty"`
	Scounter         *SimpleCounter `protobuf:"bytes,13,opt,name=scounter" json:"scounter,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *UserBase) Reset()                    { *m = UserBase{} }
func (m *UserBase) String() string            { return proto.CompactTextString(m) }
func (*UserBase) ProtoMessage()               {}
func (*UserBase) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{2} }

func (m *UserBase) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *UserBase) GetExp() uint32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *UserBase) GetMoney() uint32 {
	if m != nil && m.Money != nil {
		return *m.Money
	}
	return 0
}

func (m *UserBase) GetCoupon() uint32 {
	if m != nil && m.Coupon != nil {
		return *m.Coupon
	}
	return 0
}

func (m *UserBase) GetYuanbao() uint32 {
	if m != nil && m.Yuanbao != nil {
		return *m.Yuanbao
	}
	return 0
}

func (m *UserBase) GetTmlogin() int64 {
	if m != nil && m.Tmlogin != nil {
		return *m.Tmlogin
	}
	return 0
}

func (m *UserBase) GetTmlogout() int64 {
	if m != nil && m.Tmlogout != nil {
		return *m.Tmlogout
	}
	return 0
}

func (m *UserBase) GetContinuelogin() uint32 {
	if m != nil && m.Continuelogin != nil {
		return *m.Continuelogin
	}
	return 0
}

func (m *UserBase) GetNocountlogin() uint32 {
	if m != nil && m.Nocountlogin != nil {
		return *m.Nocountlogin
	}
	return 0
}

func (m *UserBase) GetSignreward() uint32 {
	if m != nil && m.Signreward != nil {
		return *m.Signreward
	}
	return 0
}

func (m *UserBase) GetSigntime() uint32 {
	if m != nil && m.Signtime != nil {
		return *m.Signtime
	}
	return 0
}

func (m *UserBase) GetAddrlist() []*UserAddress {
	if m != nil {
		return m.Addrlist
	}
	return nil
}

func (m *UserBase) GetScounter() *SimpleCounter {
	if m != nil {
		return m.Scounter
	}
	return nil
}

type UserAddress struct {
	Receiver         *string `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	Phone            *string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	Address          *string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserAddress) Reset()                    { *m = UserAddress{} }
func (m *UserAddress) String() string            { return proto.CompactTextString(m) }
func (*UserAddress) ProtoMessage()               {}
func (*UserAddress) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{3} }

func (m *UserAddress) GetReceiver() string {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return ""
}

func (m *UserAddress) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *UserAddress) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

type ItemData struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Num              *uint32 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	Pos              *int32  `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ItemData) Reset()                    { *m = ItemData{} }
func (m *ItemData) String() string            { return proto.CompactTextString(m) }
func (*ItemData) ProtoMessage()               {}
func (*ItemData) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{4} }

func (m *ItemData) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ItemData) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *ItemData) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type ItemBin struct {
	Items            []*ItemData `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ItemBin) Reset()                    { *m = ItemBin{} }
func (m *ItemBin) String() string            { return proto.CompactTextString(m) }
func (*ItemBin) ProtoMessage()               {}
func (*ItemBin) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{5} }

func (m *ItemBin) GetItems() []*ItemData {
	if m != nil {
		return m.Items
	}
	return nil
}

type Serialize struct {
	Entity           *EntityBase `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
	Base             *UserBase   `protobuf:"bytes,2,opt,name=base" json:"base,omitempty"`
	Item             *ItemBin    `protobuf:"bytes,3,opt,name=item" json:"item,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Serialize) Reset()                    { *m = Serialize{} }
func (m *Serialize) String() string            { return proto.CompactTextString(m) }
func (*Serialize) ProtoMessage()               {}
func (*Serialize) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{6} }

func (m *Serialize) GetEntity() *EntityBase {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *Serialize) GetBase() *UserBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *Serialize) GetItem() *ItemBin {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*EntityBase)(nil), "msg.EntityBase")
	proto.RegisterType((*SimpleCounter)(nil), "msg.SimpleCounter")
	proto.RegisterType((*UserBase)(nil), "msg.UserBase")
	proto.RegisterType((*UserAddress)(nil), "msg.UserAddress")
	proto.RegisterType((*ItemData)(nil), "msg.ItemData")
	proto.RegisterType((*ItemBin)(nil), "msg.ItemBin")
	proto.RegisterType((*Serialize)(nil), "msg.Serialize")
	proto.RegisterEnum("msg.ItemPos", ItemPos_name, ItemPos_value)
}

func init() { proto.RegisterFile("serialize.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x25, 0x9b, 0xa6, 0x4d, 0x27, 0x0d, 0x0d, 0x06, 0x24, 0xc3, 0x22, 0x6d, 0x15, 0x21, 0x51,
	0x71, 0xa8, 0x50, 0x7f, 0x00, 0x51, 0xe0, 0xc0, 0x0d, 0x51, 0x71, 0x5e, 0x79, 0x93, 0xd9, 0x60,
	0x29, 0xb6, 0x23, 0xdb, 0x29, 0x5b, 0x3e, 0x80, 0x4f, 0xe0, 0x7b, 0x91, 0xc7, 0x74, 0xd5, 0x15,
	0x47, 0x3f, 0xcf, 0xbc, 0xf7, 0xe6, 0xcd, 0xc0, 0xd2, 0xa1, 0x95, 0xa2, 0x97, 0xbf, 0x70, 0x33,
	0x58, 0xe3, 0x0d, 0x4b, 0x95, 0xeb, 0xea, 0x6f, 0x00, 0x9f, 0xb5, 0x97, 0xfe, 0xb8, 0x13, 0x0e,
	0x19, 0xc0, 0x85, 0x6c, 0x79, 0xb2, 0x4a, 0xd6, 0x13, 0xb6, 0x80, 0x89, 0x16, 0x0a, 0xf9, 0xc5,
	0x2a, 0x59, 0xcf, 0xc3, 0xeb, 0x56, 0x34, 0xc8, 0x53, 0x7a, 0x15, 0x90, 0x3a, 0xbc, 0xe3, 0x93,
	0x55, 0xb2, 0xce, 0xd8, 0x12, 0x66, 0xa2, 0x69, 0xcc, 0xa8, 0x3d, 0xcf, 0xc2, 0x6f, 0xfd, 0x3b,
	0x81, 0x72, 0x2f, 0xd5, 0xd0, 0xe3, 0xc7, 0x80, 0xa2, 0x65, 0x15, 0xe4, 0xb7, 0x16, 0xd1, 0x79,
	0x1c, 0x88, 0x3d, 0x0b, 0x48, 0x27, 0x0f, 0x11, 0x09, 0x0a, 0x29, 0x7b, 0x01, 0x4f, 0x5a, 0x29,
	0x94, 0xd1, 0xed, 0xb5, 0x35, 0x46, 0x5d, 0x37, 0xc6, 0x79, 0x92, 0x4b, 0xd9, 0x25, 0x3c, 0x7d,
	0xf0, 0x25, 0x75, 0x63, 0x14, 0x92, 0xfc, 0xff, 0x7d, 0x44, 0x19, 0x8c, 0xa4, 0xf5, 0x9f, 0x0b,
	0xc8, 0xbf, 0x3b, 0xb4, 0x34, 0x5b, 0x09, 0x59, 0x8f, 0x07, 0xec, 0xc9, 0x40, 0x19, 0x46, 0xc0,
	0xbb, 0xa8, 0x5d, 0x86, 0x3f, 0x65, 0x34, 0x1e, 0x49, 0xaf, 0x64, 0x8f, 0x61, 0xda, 0x98, 0x71,
	0x30, 0x9a, 0x24, 0xca, 0x30, 0xe1, 0x71, 0x14, 0xfa, 0x46, 0x18, 0x22, 0x26, 0xc0, 0xab, 0xde,
	0x74, 0x52, 0xf3, 0x29, 0x99, 0xa8, 0x20, 0x27, 0xc0, 0x8c, 0x9e, 0xcf, 0x08, 0x79, 0x0e, 0x65,
	0x63, 0xb4, 0x97, 0x7a, 0xc4, 0x58, 0x98, 0x53, 0xe7, 0x33, 0x58, 0x68, 0x43, 0x61, 0x45, 0x74,
	0x4e, 0x28, 0x03, 0x70, 0xb2, 0xd3, 0x16, 0x7f, 0x0a, 0xdb, 0x72, 0x20, 0xac, 0x82, 0x3c, 0x60,
	0x5e, 0x2a, 0xe4, 0x05, 0x21, 0x35, 0xe4, 0xa2, 0x6d, 0x6d, 0x2f, 0x9d, 0xe7, 0x8b, 0x55, 0xba,
	0x2e, 0xb6, 0xd5, 0x46, 0xb9, 0x6e, 0x13, 0x46, 0xfc, 0xd0, 0xb6, 0x16, 0x9d, 0x63, 0xaf, 0x21,
	0x77, 0x4d, 0x4c, 0x9d, 0x97, 0xab, 0x64, 0x5d, 0x6c, 0x19, 0xd5, 0x3c, 0xd8, 0x47, 0xfd, 0x1e,
	0x8a, 0xf3, 0xa6, 0x0a, 0x72, 0x8b, 0x0d, 0xca, 0x03, 0x5a, 0x4a, 0x67, 0x1e, 0x02, 0x19, 0x7e,
	0x18, 0x7d, 0xda, 0x7e, 0x58, 0x71, 0xac, 0x8d, 0x07, 0x50, 0xbf, 0x83, 0xfc, 0x8b, 0x47, 0xf5,
	0x49, 0x78, 0x71, 0x76, 0x34, 0x94, 0xaa, 0x1e, 0xd5, 0xbf, 0x54, 0x0b, 0x48, 0x07, 0x13, 0x3b,
	0xb2, 0xfa, 0x0d, 0xcc, 0x42, 0xc7, 0x4e, 0x6a, 0xf6, 0x0a, 0x32, 0xe9, 0x51, 0x39, 0x9e, 0xd0,
	0x10, 0x25, 0x19, 0x3c, 0xd1, 0xd5, 0x08, 0xf3, 0xfd, 0xe9, 0x52, 0xd9, 0x15, 0x4c, 0x91, 0xce,
	0x93, 0xf8, 0x8b, 0xed, 0x92, 0x6a, 0xcf, 0x2e, 0xf6, 0x12, 0x26, 0x37, 0xc2, 0x45, 0x9f, 0x27,
	0xaa, 0xfb, 0x95, 0xbf, 0x84, 0x49, 0x10, 0x22, 0x07, 0xc5, 0x76, 0x71, 0xaf, 0xb3, 0x93, 0xfa,
	0xed, 0x55, 0xf4, 0xf3, 0xd5, 0x38, 0x36, 0x83, 0x74, 0x27, 0xba, 0xea, 0x11, 0x2b, 0x60, 0xb6,
	0xf7, 0xc6, 0x8a, 0x0e, 0xab, 0xe4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x56, 0x5b, 0x01,
	0x30, 0x03, 0x00, 0x00,
}
