// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MatchServer 广播消息到其他服务器
type MS2Server_BroadCast struct {
	Cmd              *string `protobuf:"bytes,1,opt,name=cmd" json:"cmd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MS2Server_BroadCast) Reset()                    { *m = MS2Server_BroadCast{} }
func (m *MS2Server_BroadCast) String() string            { return proto.CompactTextString(m) }
func (*MS2Server_BroadCast) ProtoMessage()               {}
func (*MS2Server_BroadCast) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *MS2Server_BroadCast) GetCmd() string {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return ""
}

func init() {
	proto.RegisterType((*MS2Server_BroadCast)(nil), "msg.MS2Server_BroadCast")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 76 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x52, 0xe2,
	0x12, 0xf6, 0x0d, 0x36, 0x0a, 0x06, 0x8b, 0xc7, 0x3b, 0x15, 0xe5, 0x27, 0xa6, 0x38, 0x27, 0x16,
	0x97, 0x08, 0x71, 0x73, 0x31, 0x27, 0xe7, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x02, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xcc, 0x3b, 0x58, 0xa5, 0x37, 0x00, 0x00, 0x00,
}
