// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 添加收货地址
type C2GW_AddDeliveryAddress struct {
	Info             *UserAddress `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *C2GW_AddDeliveryAddress) Reset()                    { *m = C2GW_AddDeliveryAddress{} }
func (m *C2GW_AddDeliveryAddress) String() string            { return proto.CompactTextString(m) }
func (*C2GW_AddDeliveryAddress) ProtoMessage()               {}
func (*C2GW_AddDeliveryAddress) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *C2GW_AddDeliveryAddress) GetInfo() *UserAddress {
	if m != nil {
		return m.Info
	}
	return nil
}

// 删除地址
type C2GW_DelDeliveryAddress struct {
	Index            *uint32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GW_DelDeliveryAddress) Reset()                    { *m = C2GW_DelDeliveryAddress{} }
func (m *C2GW_DelDeliveryAddress) String() string            { return proto.CompactTextString(m) }
func (*C2GW_DelDeliveryAddress) ProtoMessage()               {}
func (*C2GW_DelDeliveryAddress) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *C2GW_DelDeliveryAddress) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

// 修改地址
type C2GW_ChangeDeliveryAddress struct {
	Index            *uint32      `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Info             *UserAddress `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *C2GW_ChangeDeliveryAddress) Reset()                    { *m = C2GW_ChangeDeliveryAddress{} }
func (m *C2GW_ChangeDeliveryAddress) String() string            { return proto.CompactTextString(m) }
func (*C2GW_ChangeDeliveryAddress) ProtoMessage()               {}
func (*C2GW_ChangeDeliveryAddress) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *C2GW_ChangeDeliveryAddress) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *C2GW_ChangeDeliveryAddress) GetInfo() *UserAddress {
	if m != nil {
		return m.Info
	}
	return nil
}

// 同步地址列表
type GW2C_SendDeliveryAddressList struct {
	List             []*UserAddress `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GW2C_SendDeliveryAddressList) Reset()                    { *m = GW2C_SendDeliveryAddressList{} }
func (m *GW2C_SendDeliveryAddressList) String() string            { return proto.CompactTextString(m) }
func (*GW2C_SendDeliveryAddressList) ProtoMessage()               {}
func (*GW2C_SendDeliveryAddressList) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

func (m *GW2C_SendDeliveryAddressList) GetList() []*UserAddress {
	if m != nil {
		return m.List
	}
	return nil
}

// 请求充值页面
type C2GW_ReqRechargeMoney struct {
	Amount           *uint32 `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	Token            *string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Type             *uint32 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GW_ReqRechargeMoney) Reset()                    { *m = C2GW_ReqRechargeMoney{} }
func (m *C2GW_ReqRechargeMoney) String() string            { return proto.CompactTextString(m) }
func (*C2GW_ReqRechargeMoney) ProtoMessage()               {}
func (*C2GW_ReqRechargeMoney) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

func (m *C2GW_ReqRechargeMoney) GetAmount() uint32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *C2GW_ReqRechargeMoney) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *C2GW_ReqRechargeMoney) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 返回充值请求
type GW2C_RetRechargeMoney struct {
	Urlcheckout      *string `protobuf:"bytes,1,opt,name=urlcheckout" json:"urlcheckout,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GW2C_RetRechargeMoney) Reset()                    { *m = GW2C_RetRechargeMoney{} }
func (m *GW2C_RetRechargeMoney) String() string            { return proto.CompactTextString(m) }
func (*GW2C_RetRechargeMoney) ProtoMessage()               {}
func (*GW2C_RetRechargeMoney) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{5} }

func (m *GW2C_RetRechargeMoney) GetUrlcheckout() string {
	if m != nil && m.Urlcheckout != nil {
		return *m.Urlcheckout
	}
	return ""
}

// 红包平台充值完成通知
type C2GW_PlatformRechargeDone struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2GW_PlatformRechargeDone) Reset()                    { *m = C2GW_PlatformRechargeDone{} }
func (m *C2GW_PlatformRechargeDone) String() string            { return proto.CompactTextString(m) }
func (*C2GW_PlatformRechargeDone) ProtoMessage()               {}
func (*C2GW_PlatformRechargeDone) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{6} }

func init() {
	proto.RegisterType((*C2GW_AddDeliveryAddress)(nil), "msg.C2GW_AddDeliveryAddress")
	proto.RegisterType((*C2GW_DelDeliveryAddress)(nil), "msg.C2GW_DelDeliveryAddress")
	proto.RegisterType((*C2GW_ChangeDeliveryAddress)(nil), "msg.C2GW_ChangeDeliveryAddress")
	proto.RegisterType((*GW2C_SendDeliveryAddressList)(nil), "msg.GW2C_SendDeliveryAddressList")
	proto.RegisterType((*C2GW_ReqRechargeMoney)(nil), "msg.C2GW_ReqRechargeMoney")
	proto.RegisterType((*GW2C_RetRechargeMoney)(nil), "msg.GW2C_RetRechargeMoney")
	proto.RegisterType((*C2GW_PlatformRechargeDone)(nil), "msg.C2GW_PlatformRechargeDone")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x41, 0x4b, 0xf3, 0x40,
	0x18, 0x84, 0xe9, 0x97, 0xf6, 0x83, 0xbe, 0x35, 0x2a, 0x91, 0x62, 0xac, 0x22, 0x25, 0xa7, 0x1e,
	0x24, 0x87, 0xdc, 0xbc, 0x08, 0x25, 0x81, 0x1e, 0x54, 0x90, 0x88, 0xf4, 0x58, 0x42, 0x32, 0x4d,
	0x96, 0x6e, 0x76, 0xeb, 0xee, 0x46, 0x8c, 0xbf, 0x5e, 0xdc, 0x46, 0xc1, 0xa2, 0x5e, 0x77, 0xe7,
	0x99, 0x79, 0x5e, 0xa2, 0x46, 0x43, 0x85, 0x5b, 0x25, 0x8d, 0xf4, 0x9c, 0x5a, 0x97, 0x93, 0x23,
	0x0d, 0xc5, 0x32, 0xce, 0xde, 0xb0, 0x7b, 0x0d, 0xae, 0xe9, 0x34, 0x8e, 0x16, 0xcb, 0xd5, 0xbc,
	0x28, 0x12, 0x70, 0xf6, 0x02, 0xd5, 0xce, 0x8b, 0x42, 0x41, 0x6b, 0xef, 0x92, 0xfa, 0x4c, 0xac,
	0xa5, 0xdf, 0x9b, 0xf6, 0x66, 0xa3, 0xe8, 0x38, 0xac, 0x75, 0x19, 0x3e, 0x69, 0xa8, 0xee, 0x3f,
	0x98, 0x75, 0x68, 0x02, 0xbe, 0x8f, 0xba, 0x34, 0x60, 0xa2, 0xc0, 0xab, 0x65, 0xdd, 0xe0, 0x96,
	0x26, 0x36, 0x19, 0x57, 0x99, 0x28, 0xf1, 0x77, 0xf8, 0x6b, 0xf6, 0xdf, 0x2f, 0xb3, 0x37, 0x74,
	0xb1, 0x58, 0x46, 0xf1, 0xea, 0x11, 0x62, 0x5f, 0xf9, 0x8e, 0x69, 0xf3, 0xc1, 0x73, 0xa6, 0x8d,
	0xdf, 0x9b, 0x3a, 0x3f, 0xf2, 0x09, 0x8d, 0xad, 0x4c, 0x8a, 0xe7, 0x14, 0x79, 0x95, 0xa9, 0x12,
	0xf7, 0x52, 0xa0, 0xf5, 0x0e, 0xe9, 0x7f, 0x56, 0xcb, 0x46, 0x98, 0x4e, 0xc4, 0xa5, 0x81, 0x91,
	0x1b, 0x08, 0x6b, 0x32, 0xf4, 0x0e, 0xa8, 0x6f, 0xda, 0x2d, 0x7c, 0xc7, 0x9e, 0x74, 0x45, 0x63,
	0x6b, 0x91, 0xc2, 0x7c, 0x6f, 0x39, 0xa1, 0x51, 0xa3, 0x78, 0x5e, 0x21, 0xdf, 0xc8, 0x66, 0x57,
	0x35, 0x0c, 0xce, 0xe9, 0xcc, 0x6e, 0x3e, 0xf0, 0xcc, 0xac, 0xa5, 0xaa, 0x3f, 0x91, 0x44, 0x0a,
	0xbc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x77, 0x62, 0x36, 0x08, 0xa5, 0x01, 0x00, 0x00,
}
